### PR TITLE
MRG: add vega expression machinery

### PR DESCRIPTION
**Pull request by jakevdp**
This PR adds a way to create validated expressions for vega formulas (addresses #208). Previously, everything had to be done with a string; for example:

```python
from altair import Chart, Formula

Chart(data).encode(
    x='x',
    y='foo',
).transform_data(
    calculate=[Formula(field='foo', expr='if(log(datum.x) < 2, "A", "B"')],
    filter='datum.x > 0'
)
```
The problem is that this string is not validated on the Python side, and the errors from Vega-Lite are not particularly helpful.

After this PR, you can instead do

```python
from altair import Chart, Formula, expr

# can pass URL, dataframe, Data obj, etc.
data = expr.DataFrame(data)

# creates a filter operation
data = data[data.x > 0]

# create a transform operation
data['foo'] = expr.if_(expr.log(data.x) < 2, "A", "B")

Chart(data).encode(
    x='x',
    y='foo',
)
```
which is more intuitive, less error-prone, and is  structurally validated on the Python side.

This is also fully backward-compatible; i.e. you can still pass the string if you wish.

### CODE REVIEW

**Comment by jakevdp** [comment]
@ellisonbg had the idea to expose this via a Pandas-like interface. I've committed some initial code that does this... still have not created the mechanism to ingest this into the spec, but that will come. The idea is we'd do something like this:

```python
from altair import Chart, expr, load_dataset

cars = load_dataset('cars', as_expr=True)
cars['newcol'] = expr.sin(cars.Miles_per_gallon / cars.Acceleration)

Chart(cars).mark_tick().encode(
    x='newcol'
)
```
and the JSON output would be something like:
```python
{
 'data': {'url': 'https://vega.github.io/vega-datasets/data/cars.json'},
 'encoding': {'x': {'field': 'newcol'}},
 'mark': 'tick',
 'transform': {'calculate': [{'field': 'newcol', 'expr': 'sin(datum.Miles_per_gallon / datum.Horsepower)'}]}
}
```

**Comment by jakevdp** [comment]
@ellisonbg I think this is ready for a review and merge, if you have a chance to take a look!

**Comment by jakevdp** [comment]
Good point on a repr for the dataframe wrapper. I think probably the most useful thing would be something like

```Data source with columns ['x', 'y', 'z']```

or

```Data source with unknown columns```

perhaps followed by a ``repr`` of the underlying object, if any.

**Comment by jakevdp** [comment]
> Is it indented to ever expand .encode to accept expr.core.Series (assuming that column is in data)?

We'd discussed that, but decided not to go that route because it would likely lead to either confusion (why doesn't this other array work?) or feature-creep (why require a dataset at all?). We might revisit that in the future.

**Comment by jakevdp** [comment]
Thanks for the review – I think I hit all the main points. I also did a couple other tweaks, such as making the default ``df`` read-only to prevent issues related to state.

**Comment by jakevdp** [comment]
Waiting on @ellisonbg to review and merge. In the meantime, I'm going to start preparing for a 1.2 release on top of this PR.

**Comment by jakevdp** [comment]
Rebased on master

**Comment by ellisonbg** [comment]
Looks great. Only one question related to `if_`. Does pandas have a method that does the equivalent thing, and if so, what is it named in pandas?

**Comment by jakevdp** [comment]
I think the closest thing is ``np.where``:

```python
>>> x = np.arange(10)
>>> np.where(x < 5, 0, 1)
array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])
```

do you think we should call it this?

**Comment by ellisonbg** [comment]
Yeah I think following the pandas API makes sense in this case. On my flight - once you make that change feel free to merge this and the subsequent ones.

**Comment by jakevdp** [comment]
If we're mapping ``if`` -> ``where``, do you think we should map other functions as well? E.g. should ``acos`` be ``arccos`` to match numpy?

**Comment by jakevdp** [comment]
I'm going to merge this, and open another issue to think about name mappings in case we want to change them

**Pull request merged**
