### PR TITLE
Update from Vega-Lite 5.6.1 to 5.7.1

### LINKED ISSUE #3020: Update to Vega-Lite 5.7
VL 5.7 just got released. Updating Altair should be straight-forward as the changes to the schema itself are very small but haven't done yet as we need to wait for https://github.com/vega/schema/issues/8 to be resolved. Before that, we can't run the schema generation for 5.7 as there is no 5.7 schema file yet available under https://vega.github.io/schema

### PR DESCRIPTION
**Pull request by binste**
I don't have a good overview if 5.7 fixes all blocking issues we had for Altair but at least on the VL GitHub repo all issues are closed.

Next up we need to again update altair_viewer so that the tests pass. @mattijn As you have done this before, do you have the cycles in the next days to do this? Totally understand if not, just let me know and I can look into it. I assume it's mainly updating and executing https://github.com/altair-viz/altair_viewer/blob/master/tools/download_scripts.py and then testing the package?

Closes #3020.

### CODE REVIEW

**Comment by mattijn** [comment]
Done per https://github.com/altair-viz/altair_viewer/pull/55.
Tests fail since vl-convert did not yet include vl5.7, cc @jonmmease.

**Comment by binste** [comment]
VL Convert 0.8 should already include VL 5.7, see https://github.com/vega/vl-convert/releases/tag/v0.8.0. Just in case you @jonmmease haven't seen it, but for a few hours there was no VL 5.7 schema available as the 5.6.1 got overwritten, see https://github.com/vega/schema/issues/8. Just in case this affected your update process for VLC but maybe this is not the issue.

**Comment by mattijn** [comment]
Hm. Ok, re-reading the GitHub actions errors it seems to fail for a few examples only? 

Can you locally see if all specifications fail to save through vl-convert or a selection of the examples only?

And if the latter, do we know which examples fail?

**Comment by binste** [comment]
vl-convert 0.8 does not work for me locally, also not against our current master branch, so I opened https://github.com/vega/vl-convert/issues/52. However, I don't get any errors at all so I'm not sure if it's the same issue as we are having here were we get some error messages.

**Comment by binste** [comment]
I think we have two separate issues to deal with. There is the one I reported for vl-convert but that does not seem to be what leads to the failures in these tests. Some examples don't work with VL 5.7 such as the "Interactive Crossfilter" example which gives `Unrecognized signal name: "param_2"`. This might be what @domoritz discovered in [this comment](https://github.com/altair-viz/altair/issues/2994#issuecomment-1484152982) three weeks ago. [Here](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUA7JQAMlAFYQ2AOxAAaEFBUAzGmTShiNOAHcDmlZhrKGbBhAAScPVjQBmGTI1blVm3YgAdRoAE3p3TwBfSI0cJAAnJAQINABtUGUkuDQQOMSEAH0AJnUQCDhBOChMczhlLRDrMhTUVJAADxAAXQ1MAE8cbPRrTDh44iRBEBiQI1MWtrmTYu7InpB4uEGkGtRQLUEGBFVWkEaITCR67I0QiqQ+0qsEbK6ZiEGocxCdlD2QbRseLIXagPLlb47IZnKHTGYMeJTdBYXD4IhQELKBQQO7CYjxSjKOCYAjKHAIXgUfg-S7lTAQAACxAAjJQigBOWQEGlIAjaYRkLAQfhFADW2JU0w08Bcu2ZHg0ggeYzSoDqDSa5gOQPME0O0IAxCFjVKOuYmNZzMh2hblC0ijIZroKiFzJttrsLIdjnCNI9-kgyGRNhRRjktAxfE8BtCAI4MK5WS5WUi+kDIeKi8z9QY5JgJU2ZF45JYrGJq+psRrKfT-Tr-W1WpA26z2x0aZ2CV3-d1wHbhtje1TRP3mQPBvhh9ARqO9GM5eOJug7GipkfphJZ-456H5+KmzCJO2A4GqgE0QSjff-PJJHK3wolaJvdaHq4QE8IM9IFogZ43TRJigBglSnDA7HiCAAAoaSOSgaTgABKaZ1hMUJwlQZkADZHUiIA) is the VL spec that is produced by Altair.

**Comment by mattijn** [comment]
Yes, I think that should be related to https://github.com/altair-viz/altair/issues/2849.

**Comment by mattijn** [comment]
I've bumped altair_viewer to [vl5.7.1](https://github.com/altair-viz/altair_viewer/pull/56) and temporarily deactivate the interactive_layered_crossfilter example to be included in the tests. 
Now all tests are passing locally and within Github Actions. Merging this, so we can continue in https://github.com/altair-viz/altair/issues/2849.

**Pull request merged**
