### PR TITLE
Update parameter docstrings and signatures

### PR DESCRIPTION
**Pull request by ChristopherDavisUCI**
Addresses #2692.

Adds more complete docstrings and signatures for parameter creation functions.  Also deprecates `selection` (in favor of `selection_point` and `selection_interval`).

Although this is primarily about documentation, the signatures were changed, so it is worth checking this carefully.  I did go through the examples [here](https://joelostblom.github.io/altair-docs/user_guide/interactions.html) and they seem to still be working.

This parameters portion of Altair has more customization and divergence from Vega-Lite (I gave one example in https://github.com/altair-viz/altair/issues/2692#issuecomment-1436026066), so these changes will not automatically be updated if changes happen in the Vega-Lite schema.  If anyone sees a more robust way to accomplish this, please let me know or feel free to make changes!

In the doc strings, I just approximated how long of lines we typically used in docstrings and inserted line breaks at corresponding locations.  I'm not sure if there is a way to have VS Code or something else automate that process, or if it's a problem that there is probably some inconsistency in terms of the exact lengths of the lines.

### CODE REVIEW

**Comment by mattijn** [comment]
Thanks @ChristopherDavisUCI! One short comment, I miss the dictating value `expr` in `param` (`alt.param(expr=...)`).

**Comment by ChristopherDavisUCI** [comment]
Thanks @mattijn, I added `expr` just now.  There aren't any `expr` examples here https://joelostblom.github.io/altair-docs/user_guide/interactions.html, do you think one should be included?

There were a few uncertainties like the following.  In https://vega.github.io/vega-lite/docs/parameter.html#expr the type of `expr` is listed as `Expr`, so I put expr : :class:`Expr` (optional) for consistency.  In practice, I think most people will use a string.  Would it be better to have expr : string or :class:`Expr` or maybe some other version?

**Comment by joelostblom** [comment]
Thanks for working on this! I think improved docstrings would be helpful here. Regarding expanding the docs for expressions I also agree that this is need and opened https://github.com/altair-viz/altair/issues/2904 yesterday with what I think would be ideal to have in an `expr` section in the docs.

**Comment by binste** [comment]
Great to have better docstrings and signatures! Just briefly, I saw that there are some __doc__ assignments which I'm not sure if they work in vs code for the same reasoning as we are discussing in the issue about ".encode". I'm on my phone now but could test this until Friday.

**Comment by mattijn** [comment]
> Also deprecates selection (in favor of selection_point and selection_interval).

Can you do this in a separate PR? Then we can also use that PR to replace the occurrences where `alt.selection(type='interval')` currently is used in the docs.

**Comment by binste** [comment]
I see why it would be convenient to define more of the docstrings using assingments to `__doc__`. However, they won't show up in IDEs such as VS Code. See #2920 for some context on why it doesn't work. With your change:

image

Without it:

image

I'd be in favour of accepting the duplication of text across docstrings (something that is done quite often in other libraries as well) so that we have the broadest possible coverage across editors, notebook environments, etc.

**Comment by mattijn** [comment]
Thanks @ChristopherDavisUCI! Do you know if we have covered somewhere the interval selection properties? Such as these from `mark`: https://vega.github.io/vega-lite/docs/selection.html#mark. 

For e.g. setting the `cursor` to a `pointer` when hovering over a select type.

**Comment by ChristopherDavisUCI** [comment]
Hi @mattijn, yes, I think so, does this count? https://github.com/altair-viz/altair/blob/5607dfcff455f3897782ac6b54d9e9d927a78f27/altair/vegalite/v5/api.py#L503-L506
I tried to copy-paste from the Vega-Lite documentation on parameters, but I might have missed some (like the `expr` you caught a few days ago).

**Comment by binste** [comment]
> Thanks @binste for letting me know about that downside of setting `__doc__` programmatically. Can you check this latest version and see if it's working in VS Code as you expect?

Docstrings defined like this are great, thanks! :)

**Comment by mattijn** [comment]
Following the docstring I tried the following, from t[his doc-example](https://joelostblom.github.io/altair-docs/user_guide/interactions.html#interactions-rst-altair-source-17):
```python
point_mouseover = alt.selection_point(
    on='mouseover', 
    toggle=False, 
    empty=False
).mark(cursor='pointer')

make_example(point_mouseover)
```
But got an
```cmd
TypeError: 'GetAttrExpression' object is not callable
```
Wish: method chaining everwhere:).

But I think it needs to be done as such:
```python
point_mouseover = alt.selection_point(
    on='mouseover', 
    toggle=False, 
    empty=False, 
    mark=alt.MarkConfig(cursor='pointer')
)

make_example(point_mouseover)
```
But that gives me this error:
```txt
type        fields    resolve   
clear       nearest   toggle    
encodings   on                  

See the help for `PointSelectionConfig` to read the full description of these parameters
```
Nice error message though!

**Comment by ChristopherDavisUCI** [comment]
Hi @mattijn, is the point that this option is only available for `selection_interval` and not `selection_point`?  But I might be missing the main issue.

**Comment by mattijn** [comment]
Oops, my bad, `mark` is only valid for `selection_interval`:
```python
interval = alt.selection_interval(mark=alt.MarkConfig(cursor='pointer'))
make_example(interval)
```
All good then. I've another comment, but will add to another issue. Nice. Since this is also reviewed by @binste, will merge it in! Thanks @ChristopherDavisUCI

**Pull request merged**
