### PR TITLE
MAINT: use pkgutil rather than open() to access internal data files

### PR DESCRIPTION
**Pull request by jakevdp**
This is necessary to work properly within Google's internal Colab deployment.

### CODE REVIEW

**Comment by jakevdp** [comment]
cc/ @craigcitro

**Comment by craigcitro** [comment]
Thanks!

And 😭 on the need to decode the result for python 3.5, but happy about https://docs.python.org/3/whatsnew/3.6.html#json.

**Comment by jakevdp** [comment]
Yep... just installed a py35 environment to test this locally...

**Comment by jakevdp** [comment]
Looks good 😎

**Pull request merged**
