### PR TITLE
Test vl-convert engine in chart.save test

### PR DESCRIPTION
**Pull request by jonmmease**
Follow on to https://github.com/altair-viz/altair/pull/2701 that addresses https://github.com/altair-viz/altair/pull/2701#issuecomment-1334413985 by updating the chart.save test to test both altair_saver and vl-convert.

I also updated a few function signatures to include the engine argument explicitly along with the engine docstring.

### CODE REVIEW

**Comment by jonmmease** [comment]
cc @joelostblom

**Comment by mattijn** [comment]
Looks good! Can you update your branch to become in sync with the main repository? There were recently some more changes to the `save()` function in altair/utils/save.py

**Comment by jonmmease** [comment]
done

**Comment by mattijn** [comment]
Thanks!

**Comment by joelostblom** [comment]
Great, thank you for following up on this @jonmmease !

**Pull request merged**
