### PR TITLE
DOC: the most minor of typos

### PR DESCRIPTION
**Pull request by phobson**
Ahead of the final release, I figured I could contribute by reviewing the docs with my somewhat naive eyes.

Here's the only change I can propose so far. 

Merge if now if you want, or I can continue going through the docs later tonight (US/Pacific TZ).

### CODE REVIEW

**Comment by jakevdp** [comment]
Thanks! If you think you'll have more, I'll leave this open for a bit so they can all go on one PR.

**Comment by phobson** [comment]
I'll holler back at you later tonight then. The docs really are so well done. It's not problem dig a little more.

**Comment by phobson** [comment]
OK, this is as far as I'll be able to take this for a while. But I'm happy to address minor comment, or let you push to my branch.

**Comment by jakevdp** [comment]
Sounds good – thanks!

**Pull request merged**
