### PR TITLE
Refactored 'savechart' as the more concise 'save'

### PR DESCRIPTION
**Pull request by palewire**
As discussed in #557

### CODE REVIEW

**Comment by jakevdp** [comment]
Looks good!

We should keep a ``savechart()`` method for the time being that raises a DeprecationWarning and then calls save().

**Comment by palewire** [comment]
I *think* I can pull that off.

**Comment by palewire** [comment]
I think I got that in with https://github.com/altair-viz/altair/pull/641/commits/ac121ad7c13c6161eb77fe374da613e1a6c458e8 but I haven't done one of these before so correct me where I screwed it up.

**Comment by jakevdp** [comment]
Looks good – minor change, I'd say that savechart "is" deprecated, not that it will soon be...

Also, no need to test the deprecated version.

**Comment by palewire** [comment]
Done in https://github.com/altair-viz/altair/pull/641/commits/492ffd08ada14cc4d85218de65450dc2e80c9da4

**Comment by jakevdp** [comment]
Looks good, thanks!

**Pull request merged**
