### PR TITLE
Do not convert categoricals to strings

### PR DESCRIPTION
**Pull request by brainstorm**
Related with #940 as I explore a way to solve the columnar sorting...

https://github.com/pandas-dev/pandas/issues/10778 is fixed upstream now

### CODE REVIEW

**Comment by jakevdp** [comment]
What's the benefit of removing this conversion?

**Comment by brainstorm** [comment]
Perhaps down the line Altair will be able to sort (columns) based on categoricals? If we cast to `str` that metadata (ordering) is lost?... but granted, I don't have a global understanding of Altair yet :-S

**Comment by jakevdp** [comment]
After sanitization, the data is converted to JSON, in which case categoricals are converted to strings anyway. JSON does not have a categorical type, so there's no way to maintain sorting of categories when converting the data to the format needed for Altair.

The sanitization code serves to ensure that people with older versions of Pandas don't get an error – it doesn't change anything about how data is represented in the end.

**Comment by brainstorm** [comment]
Oh, I see, backwards compat issues, gotcha :-S

In any case, that bug has been solved 2 years ago, so worst case it'll prompt people to upgrade their pandas installations? If the conversion to str happens downstream anyway when converting to JSON, this PR could be labeled as a maintenance enhancement since it does remove `XXX`'s.

**Comment by jakevdp** [comment]
I don't really see any benefit to the change, and there is the distinct downside that it will re-introduce a bug that was already fixed for previous pandas versions. There are many situations in which people might be using old library versions and not be able to easily upgrade.

I'm going to close this – thanks for the contribution!

**Pull request closed without merging**
