### PR TITLE
Update from Vega-Lite 5.2.0 to 5.6.1

### PR DESCRIPTION
**Pull request by ChristopherDavisUCI**
Based on the [release notes](https://github.com/vega/vega-lite/releases/tag/v5.6.0) for Vega-Lite 5.6.0, I tried setting `zero=False` as the scale configuration default.

```
import altair as alt
from vega_datasets import data

cars = data.cars.url

c = alt.Chart(cars).mark_circle().encode(
    x = "Weight_in_lbs:Q",
    y = "Acceleration:Q"
).properties(
    height=100,
    width=100
).configure_scale(
    zero=False,
)
```

No errors are raised (even when using `validate="deep"`), whereas errors are raised if I use this code with the current version on GitHub. I take that as a good sign.

On the other hand, the displayed chart doesn't reflect this change:
chart

Maybe vega-embed is not matching vega-lite 5.6 yet? That's my first guess.

### CODE REVIEW

**Comment by ChristopherDavisUCI** [comment]
I haven't investigated the failing tests, but my first guess is that 5.2 needs to be updated to 5.6 in some other places, like `altair_viewer`?  Maybe [this comment](https://github.com/altair-viz/altair/pull/2528#issuecomment-1013851890) is relevant?

If it's failing because of a reason I can help with, please let me know!

**Comment by mattijn** [comment]
We've to supersede this PR:  https://github.com/altair-viz/altair_viewer/pull/51 in altair_viewer.

**Comment by joelostblom** [comment]
Thanks @ChristopherDavisUCI ! The changes here look good to me, but let's wait until we have updated altair_viewer to support 5.6 as @mattijn mentioned, so that we can be sure that the tests pass.

**Comment by ChristopherDavisUCI** [comment]
Hi @mattijn, it looks like at least one of the issues is the same one as reported here: https://github.com/altair-viz/altair/issues/2856 (same example, same error).  Do you see why that error is coming up on this PR and not on every PR?

Another issue involves `mimebundle`, but at first glance I don't have anything to add.

**Comment by mattijn** [comment]
This specification renders in Altair.
But the interaction only works once.

```python
import altair as alt
from vega_datasets import data

source = data.cars.url

bind_checkbox = alt.binding_checkbox(name='checkbox')
param_checkbox = alt.selection_point(bind=bind_checkbox)

cond_checkbox = alt.condition(
    param_checkbox,
    alt.value(25),
    alt.Size('Acceleration:Q')
)

chart = alt.Chart(source).mark_circle().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
    size=cond_checkbox
).add_params(param_checkbox)
chart
```

image

Once trying to save the chart as `png` or `svg`, it will provide the same error as when you [open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAZgAY2AacaYsiygAlMiRoVYcAvpO50AhoTl4QpAE4AbFCDGEADpWQB6Q2DpQAdACtKdTOrhpV5qJkKGougLaG0mBHIBaeUVKV0oAATQARnMAJgBOczZDYLkTOVVKK0poEBkQTwyAa2VCAE9dTC0wOFUwdSr8zChIOhIkVBBKOAAvKs6CNuJczt0MuU8tMdUJgH0ogA4QbjQ5dVJ+2IBWfPg7Oi0AQTAwO0wZ4ahlkHLKrQBHUjkiOEViXzzuAA9lPfUD5AgQQQTKYXQQbDna63fogR7PYhvByNbhlX5Yf5aACycAalFmlVUswA4mt1LluDCHk8XkiPtJuNMJpQUABtUBQCawpmeeZLbihBpgcSdKmA8EkcT5ABGJABoBIulIIvAjEwYCK0ogP24nM8sLAao1Wp+0gAutwACSUQ2YQpaHT6Iw+PxycwIV6MUjS8xwCCGG1qwou-wBeyETA+LbmABs5hi1lykiAA).
```python
chart.save('chart.svg')
```
```cmd
ValueError: Vega to SVG conversion failed:
Error: Unrecognized signal name: "param_18_tuple_fields"
    at b (https://cdn.skypack.dev/-/vega-util@v1.17.0-uRskU0IBL2vWCP4Va8OC/dist=es2020,mode=imports,min/optimized/vega-util.js:1:324)
    at ue.getSignal (https://cdn.skypack.dev/-/vega-parser@v6.1.4-PbzshukasZitnbnp29GQ/dist=es2020,mode=imports,min/optimized/vega-parser.js:1:43806)
    at https://cdn.skypack.dev/-/vega-functions@v5.12.1-G6oHWIVrVbJOnq67V4GW/dist=es2020,mode=imports,min/optimized/vega-functions.js:1:11264
    at Array.forEach (<anonymous>)
    at Nn (https://cdn.skypack.dev/-/vega-functions@v5.12.1-G6oHWIVrVbJOnq67V4GW/dist=es2020,mode=imports,min/optimized/vega-functions.js:1:11229)
    at Pe (https://cdn.skypack.dev/-/vega-parser@v6.1.4-PbzshukasZitnbnp29GQ/dist=es2020,mode=imports,min/optimized/vega-parser.js:1:8014)
    at https://cdn.skypack.dev/-/vega-parser@v6.1.4-PbzshukasZitnbnp29GQ/dist=es2020,mode=imports,min/optimized/vega-parser.js:1:39038
    at Array.forEach (<anonymous>)
    at hn (https://cdn.skypack.dev/-/vega-parser@v6.1.4-PbzshukasZitnbnp29GQ/dist=es2020,mode=imports,min/optimized/vega-parser.js:1:39027)
    at al (https://cdn.skypack.dev/-/vega-parser@v6.1.4-PbzshukasZitnbnp29GQ/dist=es2020,mode=imports,min/optimized/vega-parser.js:1:39762)
```

**Comment by mattijn** [comment]
I temporarily removed the sub chart (bottom-right) that is binded to `alt.binding_checkbox(name='checkbox')` in https://altair-viz.github.io/gallery/multiple_interactions.html. Now checks are passing. Once it is fixed in VL than we can turn on this sub chart again.

**Comment by mattijn** [comment]
You agree @joelostblom?

**Comment by joelostblom** [comment]
I think that instead of removing the chart, we could change it based on the comment in https://github.com/vega/vega-lite/issues/4870#issuecomment-832837073:

```diff
- param_checkbox = alt.selection_point(bind=bind_checkbox)
+ param_checkbox = alt.param(bind=bind_checkbox)
```

This makes the example work for me, maybe we should update all checkpoint examples to use this approach?

**Comment by mattijn** [comment]
Good memory! Make sense👍

**Comment by ChristopherDavisUCI** [comment]
Hi @joelostblom @mattijn I'm going to be traveling the next few days, so please go ahead and make any changes if you see anything that should be done soon.  Otherwise I should be back on schedule Monday.

**Comment by mattijn** [comment]
Updated as you suggested @joelostblom. Tests pass now, merging.

**Pull request merged**
