### PR TITLE
ENH: Add William Playfair Wheat and Wages example

### PR DESCRIPTION
**Pull request by pratapvardhan**
image

### CODE REVIEW

**Comment by jakevdp** [comment]
Looks great! We have a simpler version of this chart here: https://altair-viz.github.io/gallery/bar_and_line_with_dual_axis.html

I still think this more polished version is a good addition to the examples. Would you mind linking to that in the description? If you use something like the following, the sphinx build will generate the correct link:

```
This is a more polished version of the simpler chart in :ref:`_gallery_bar_and_line_with_dual_axis`.
```

**Comment by jakevdp** [comment]
In the other example header, you could also add something like this:
```
For a more polished version of this chart, see :ref:`_gallery_wheat_wages`.
```

**Comment by pratapvardhan** [comment]
Updated with crosslinks.

**Comment by jakevdp** [comment]
Looks great, thanks!

**Pull request merged**
