### PR TITLE
added vega-lite example of falkensee

### PR DESCRIPTION
**Pull request by afonit**
This has one issue:
When building the final chart
chart = line + recta + point

recta should be in the first position so it does not cover up the lines and points, but if I put recta there errors will result.  line + point + recta work fine as well, just (at this point) can't have recta in first position where it needs to be for the visual composition to work.

The errors are: KeyError: 'population'

I am assuming vega-lite is expecting the full axis with the item in first position - or it is building components before they are loaded(since population is only in the line/points data and not recta's data)?

The vega-lite example is here:
https://vega.github.io/vega-lite/examples/layer_falkensee.html

### CODE REVIEW

**Comment by jakevdp** [comment]
Ah, I think I know why this is happening. It has to do with how the ``context`` variable is handled within the recursive call of ``to_dict``. Let me see if I can fix it.

**Comment by jakevdp** [comment]
OK, I think I got it. Once #486 is merged, you'll be able to do ``recta + line + point`` and there won't be an error.

**Comment by afonit** [comment]
Great once I see it merged I will reinstall and rerun the chart. Thank you.

**Comment by jakevdp** [comment]
Looks good!

**Pull request merged**
