### PR TITLE
update troubleshooting guide for empty charts caused by adblocker

### PR DESCRIPTION
**Pull request by corriebar**
This would have helped me in this situation.

### CODE REVIEW

**Comment by jakevdp** [comment]
I think this is a useful addition, but it would be better if there were a few sentences about what causes the issue and how it can be fixed.

**Comment by corriebar** [comment]
Unfortunately, I'm not quite sure what causes it. I assume it is because of some Javascript code that is blocked by common adblocker. If this is enough as an explanation, I can add it.

**Comment by jakevdp** [comment]
Even if there's no explanation of why it causes an issue, a sentence about how to fix the issue would be useful. I don't know how to fix it, because I've never seen this issue myself.

**Comment by corriebar** [comment]
I added a short sentence on how to fix the empty plot (deactivate adblocker).

**Comment by jakevdp** [comment]
Thanks!

**Comment by Kaligule** [comment]
Congratulations to @corriebar to your first successfull merge request. You can now safly delete your fork of altair. :tada:

**Pull request merged**
