### PR TITLE
Use ISO format for dates to prevent timezone issues

### LINKED ISSUE #1027: Monthly data and ordinal encoding create an "off by one" error
I uncovered this "bug" during some data exploration for development of a [open-source library](https://github.com/datadesk/cpi/blob/master/notebooks/analysis.ipynb) tracking the U.S. Consumer Price Index. 

The source data is monthly, with the values linked with the first date of each month. 

```python
import pandas as pd
import altair as alt
df = pd.read_json("https://raw.githubusercontent.com/datadesk/cpi/master/notebooks/last_13.json", dtype={"date_label": pd.np.datetime64})
df.head(13)[['date',  'pct_change_rounded']]
```

screenshot from 2018-07-16 18-33-09

My aim was to format the dates in the x-axis labels in the same manner as the government's sample chart.

screenshot from 2018-07-16 18-36-58

I tried to do that with `timeUnit` and the `format` option to `axis`.

```python
alt.Chart(df).mark_bar().encode(
    x=alt.X("date:O", timeUnit="yearmonth", axis=alt.Axis(format="%b %y")),
    y="pct_change_rounded:Q"
)
```

Here's what I got:

visualization 39

Look closely and you can see that the latest value, June 1, is rendered as May.

What's up with that?

### PR DESCRIPTION
**Pull request by jakevdp**
Fixes #1027 

@palewire – please confirm that this fixes your issue! I've run your example from #1027 with this change, and it seems to be working as expected:
```python
import pandas as pd
import altair as alt
df = pd.read_json("https://raw.githubusercontent.com/datadesk/cpi/master/notebooks/last_13.json", dtype={"date_label": pd.np.datetime64})

alt.Chart(df).mark_bar().encode(
    x=alt.X("date:O", timeUnit="yearmonth", axis=alt.Axis(format="%b %y")),
    y="pct_change_rounded:Q"
)
```
visualization 28

### CODE REVIEW

**Comment by jakevdp** [comment]
Additionally, if you explicitly set the time in the pandas data to a time-zone aware UTC date, it will adjust to the local time of the person visualizing the data. For example, this explicitly localizes the time to New York, and the visualization will be adjusted to the viewer's local time.
```python
import pandas as pd
import altair as alt
df = pd.read_json("https://raw.githubusercontent.com/datadesk/cpi/master/notebooks/last_13.json", dtype={"date_label": pd.np.datetime64})

df['date'] = df.date.dt.tz_localize("America/New_York")

alt.Chart(df).mark_bar().encode(
    x=alt.X("date:O", timeUnit="yearmonth", axis=alt.Axis(format="%b %y")),
    y="pct_change_rounded:Q"
)
```

**Comment by palewire** [comment]
It's fixed! You can see the result in [my more fully formed notebook](https://nbviewer.jupyter.org/github/datadesk/cpi/blob/master/notebooks/analysis.ipynb).

**Comment by jakevdp** [comment]
Great!

**Comment by domoritz** [comment]
Thanks for digging into this @jakevdp! It's always a sign that it was a lot of work when the patch adds a long comment for a small code change.

**Comment by mattijn** [comment]
I wrote an example that can be used for documentation:



```python
import pandas as pd
import altair as alt
```


```python
dates = pd.date_range(start='2018-8-11 23:00', end='2018-8-15 23:00')#, tz='Europe/Amsterdam')
df = pd.DataFrame({'date': dates, 'value': [2,4,5,1,6]})
df.head()
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>date</th>
      <th>value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2018-08-11 23:00:00</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2018-08-12 23:00:00</td>
      <td>4</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2018-08-13 23:00:00</td>
      <td>5</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2018-08-14 23:00:00</td>
      <td>1</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2018-08-15 23:00:00</td>
      <td>6</td>
    </tr>
  </tbody>
</table>
</div>

```python
# discretization of time using timeUnit and custom date format
alt.Chart(df).mark_bar().encode(
    x="value:N",    
    y=alt.X("date:O", 
            timeUnit="yearmonthdatehoursminutes", 
            axis=alt.Axis(format='%A %H:%M (%b, %Y)', title='date')
           )
)
```

output_2_0

```python
# if you localize the date in your data in a certain timezone
# this example works well with a timezone 2 hours westwards of your current
# timezone (since I'm currently in timezone CEST I use GMT)
df['date'] = df.date.dt.tz_localize("GMT")

# then Altair will use the local timezone for visualising the data.
alt.Chart(df).mark_bar().encode(
    x="value:N",    
    y=alt.X("date:O", 
            timeUnit="yearmonthdatehoursminutes", 
            axis=alt.Axis(format='%A %H:%M (%b, %Y)', title='date')
           )
)
```

output_3_0

```python
# without making your date timezone aware, Altair also has an option to 
# present your date in UTC, where it assumes the local timezone of the 
# date provided. For this use the prefix `utc` in timeUnit.
df['date'] = df.date.dt.tz_localize(None)
alt.Chart(df).mark_bar().encode(
    x="value:N",    
    y=alt.X("date:O", 
            timeUnit="utcyearmonthdatehoursminutes", 
            axis=alt.Axis(format='%A %H:%M (%b, %Y)', title='date')
           )
)
```
output_4_0

**Comment by mattijn** [comment]
Huh, it seems I wrote previous comment altair 2.1? Because now behaviour is different. This surely needs better documentation. I've to parse date now as UTC string, and should not specify `timeUnit`.

```python
import altair as alt
import pandas as pd

dates = pd.date_range(start='2018-8-11 23:00', end='2018-8-15 23:00')
dates = dates.strftime ("%Y-%m-%d %H:%M:%S")
df = pd.DataFrame({'date': dates, 'value': [2,4,5,1,6]})
df.head()
```

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>date</th>
      <th>value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2018-08-11 23:00:00</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2018-08-12 23:00:00</td>
      <td>4</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2018-08-13 23:00:00</td>
      <td>5</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2018-08-14 23:00:00</td>
      <td>1</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2018-08-15 23:00:00</td>
      <td>6</td>
    </tr>
  </tbody>
</table>


```python
# use only custom date format
alt.Chart(df).mark_bar().encode(
    x="value:N",    
    y=alt.X("date:O", 
            #timeUnit="yearmonthdatehoursminutes", 
            axis=alt.Axis(format='%A %H:%M (%b, %Y)', title='date')
           )
)
```
erg

If I don't use `.strftime ("%Y-%m-%d %H:%M:%S")`, dates are seen as ISO date and parsed as GMT date so it renders in Altair as my local time zone:

```python
dates = pd.date_range(start='2018-8-11 23:00', end='2018-8-15 23:00')
#dates = dates.strftime ("%Y-%m-%d %H:%M:%S")
df = pd.DataFrame({'date': dates, 'value': [2,4,5,1,6]})

alt.Chart(df).mark_bar().encode(
    x="value:N",    
    y=alt.X("date:O", 
            timeUnit="yearmonthdatehoursminutes", 
            axis=alt.Axis(format='%A %H:%M (%b, %Y)', title='date')
           )
)
```
er2

**Comment by jakevdp** [comment]
interesing. I didn't know anything had changed in that area.

**Comment by jakevdp** [comment]
Actually, that's probably due to the PR I made in response to this issue. 2.1 will not handle time zones correctly.

**Comment by mattijn** [comment]
Thats what I expected as well, but if I did not use `strftime` and not localize my dates it did not show up as local time. 

My dates were observed as UTC time zone and from there calculated to local

See my last snippet in my last comment.

But in your code snippet it seems to work alright, let me double check today if I find some time.

**Comment by mattijn** [comment]
If I copy your code+paste and run the snippet, I see the following:
er3

Maybe it might be necessary to set explicit the local timezone information of the user when parsing to ISO dates. Since the following works:

```python
from tzlocal import get_localzone
local_tz = get_localzone()
print(local_tz)
```
```
Europe/Amsterdam
```
```python
dates = pd.date_range(start='2018-8-11 23:00', end='2018-8-15 23:00')
df = pd.DataFrame({'date_local_explicit': dates.tz_localize(local_tz),
                   'date_utc': dates.tz_localize("America/New_York"),
                   'value': [2,4,5,1,6]})

left = alt.Chart(df).mark_bar().encode(
    x="value:N",    
    y=alt.X("date_local_explicit:O", 
            timeUnit="yearmonthdatehoursminutes", 
            axis=alt.Axis(format='%A %H:%M (%b, %Y)', title='date')
           )
)

right = alt.Chart(df).mark_bar().encode(
    x="value:N",    
    y=alt.X("date_utc:O", 
            timeUnit="yearmonthdatehoursminutes", 
            axis=alt.Axis(format='%A %H:%M (%b, %Y)', title='date')
           )
)

left | right
```
er4

**Comment by mattijn** [comment]
I just wish you are right, but yes my version of Altair contains this pull request. I removed my version of Altair and created a new git clone. This line:

```python
df[col_name] = df[col_name].apply(lambda x: x.isoformat()).replace('NaT', '')
```

is included and when I put a print statement before it, it is executed during rendering of the visualisation.

Moreover, when I read this text you referring to ([differences_in_assumed_time_zone](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#Differences_in_assumed_time_zone))
it states:

> Given a date string of "March 7, 2014", parse() assumes a local time zone, but given an ISO format such as "2014-03-07" it will assume a time zone of UTC (ES5 and ECMAScript 2015).

I've the feeling that this is the behaviour I see. My dates are parsed in ISO format, the timezone is assumed to be UTC accordingly and from there it is converted to my local time.

I'm confused why this code is working fine on your machine

**Comment by jakevdp** [comment]
> My dates are parsed in ISO format, the timezone is assumed to be UTC accordingly and from there it is converted to my local time.

What browser are you using? The other complication here is (I believe) different browser implementations handle javascript date parsing differently.

**Comment by jakevdp** [comment]
If you open your javascript console and type the following two lines, what do you get?
```js
> Date.parse('2012-01-01T23:00:00')
  1325487600000
> Date.parse('2012-01-01T23:00:00Z')
  1325458800000
```

**Comment by mattijn** [comment]
As the second one..

```javascript
Date.parse('2012-01-01T23:00:00Z')
1325458800000
```

**Comment by mattijn** [comment]
I'm on Safari by the way. 

I further tried:

```python
df['date_local'] = df['date_local'].apply(
    lambda x: x.tz_localize(timezone.utc).timestamp()*1000
).replace('NaT', '')
```
to convert dates to milliseconds since Unix epoch. But this only works if the date provided is in UTC. An attempt to avoid `.isoformat()` and `strftime`, but timestamps are parsed as if they are presented in UTC. Meaning I first should convert the dates to UTC using my local timezone (`tzlocal`).

And then I tried a `'  '` separator in `.isoformat()` instead of `'T'`:

```python
df['date_local'] = df['date_local'].apply(lambda x: x.isoformat(' ')).replace('NaT', '')
```

but this results in the same effect as using `.strftime("%Y-%m-%d %H:%M:%S")`

The more I try, I just think you've to explicit set the local time zone using something as `tzlocal`

**Comment by mattijn** [comment]
Chrome:
```javascript
Date.parse('2012-01-01T23:00:00Z')
1325458800000
```

Firefox
```javascript
Date.parse('2012-01-01T23:00:00Z')
1325458800000
```

**Comment by domoritz** [comment]
Safari behaves differently when the format is not a format specified in the ecma script standard.

**Comment by mattijn** [comment]
Confirmed. The behaviour only happens in Safari. In both Firefox and Chrome it renders correctly

**Comment by mattijn** [comment]
I read ES6 documentation on string format: https://tc39.github.io/ecma262/#sec-date-time-string-format
And the blog of Matt on ES6: https://codeofmatt.com/2015/06/17/javascript-date-parsing-changes-in-es6/ 

And I don't know how to go on next. Maybe Vega(-lite) should adopt moment.js for date parsing as of suggestion of Matt's blog and comment: 

> My advice - stay away from the Date object for parsing. It's just too unreliable. Use moment.js instead.

**Comment by jakevdp** [comment]
> As the second one..

What happens if you try the first one?

**Comment by jakevdp** [comment]
OK, I checked in Safari and confirmed that it interpret dates of the form ``'2012-01-01T23:00:00'`` as UTC, whereas Chrome and Firefox interpret them as local time.

So the fix in this PR does not work for Safari.

Honestly, at this point I'm tempted to just write the docs for Chrome/Firefox and just put a warning that Safari is not supported due to inconsistencies in how it handles datetimes.

**Comment by domoritz** [comment]
If you add a Z, all browsers interpret the date the same (as UTC)

Chrome:
screen shot 2018-08-12 at 15 54 36

Safari:
screen shot 2018-08-12 at 15 54 30

Given that this is such a mess in JavaScript and the problem is not only coming up in Altair, I think Vega should really implement its own date parsing with momentjs.

**Comment by domoritz** [comment]
Here is a list of good js date parsing libs: https://stackoverflow.com/questions/15141762/how-to-initialize-javascript-date-to-a-particular-timezone/15171030#15171030

**Comment by domoritz** [comment]
Another option is for Altair to explicitly tell Vega to parse dates as UTC. Here is the reader code: https://github.com/vega/vega-loader/blob/master/src/read.js.

**Comment by jakevdp** [comment]
My choice in Altair was to output dates so that they would be parsed as local dates, just as they are displayed as local dates. That's far less confusing to users than having Vega-lite silently convert time-zones unless you change the default date representation and use UTC.

Turns out it works everywhere but Safari.

I think we'll just keep it as-is, and document that Safari is not supported.

**Comment by mattijn** [comment]
Agreed. An improved date-handling in Vega(-lite) is in the long-run a better solution.

A (temporary) solution that also works in all browsers for Altair is to serialize generic dates to local dates including local time zone. 
Cons: new dependency.

**Comment by jakevdp** [comment]
I added some timezone docs here: #1087

**Pull request merged**
