### PR TITLE
Create new sections in the gallery for distributions and uncertainties and trend charts

### PR DESCRIPTION
**Pull request by binste**
@joelostblom I created the two new sections in the example gallery which you proposed in #2696. I hosted the documentation based on this pull request at https://binste.github.io/altair-docs/index.html so it's easier to review. I also took the liberty to harmonize the titles of the examples in a separate commit, e.g. title case, consistently use "Scatter Plot" instead of mix with "Scatterplot", etc.

Open questions from my side:

- [x] All examples in the "Tables" section, except for maybe the Wind Vector Map, could also be moved into the newly created "Distributions" section (in your issue you mentioned the [binned histogram](https://binste.github.io/altair-docs/gallery/binned_heatmap.html)). I'd suggest to do this, what do you think?
- [x] As discussed, I rewrote the [Strip Plot with Jitter](https://binste.github.io/altair-docs/gallery/strip_plot_jitter.html) example using the new offset encoding. However, it's now almost the same as [Jitter Chart](https://binste.github.io/altair-docs/gallery/jitter_chart.html) which has a better description. What about removing Jitter Chart and adding the reasoning of why using jitter to the "Strip Plot with Jitter" chart?
- [x] The category "Other Charts" is currently empty but shows up at the bottom of the gallery. Ok if I remove it? I saw that it is used as a fallback category for unclassified examples but we could also just raise an error or warning if this happens.

### CODE REVIEW

**Comment by mattijn** [comment]
The table section is based on the table-based plots from vega-lite. I like this section https://vega.github.io/vega-lite/examples/#table-based-plots and maybe we can do both? Expand the table section a bit more and move some to the distribution section? 
The wind vector map is a bit odd there. That one could be added to the Maps section if we add a base layer*.

I favour the strip plot with jitter. So from me +1 to take the description and from the jitter chart and remove the jitter chart.

OK, for error/warning when removing empty other charts.

/* eg like this:
```python
import altair as alt
from vega_datasets import data

df_wind = data.windvectors()
data_world = alt.topo_feature(data.world_110m.url, "countries")

wedge = (
    alt.Chart(df_wind)
    .mark_point(shape="wedge", filled=True)
    .encode(
        latitude="latitude",
        longitude="longitude",
        color=alt.Color(
            "dir", scale=alt.Scale(domain=[0, 360], scheme="rainbow"), legend=None
        ),
        angle=alt.Angle("dir", scale=alt.Scale(domain=[0, 360], range=[180, 540])),
        size=alt.Size("speed", scale=alt.Scale(rangeMax=500)),
    )
    .project("equalEarth")
)

xmin, xmax, ymin, ymax = (
    df_wind.longitude.min(),
    df_wind.longitude.max(),
    df_wind.latitude.min(),
    df_wind.latitude.max(),
)

# clockwise, left-hand-rule
extent = [
    {
        "type": "Polygon",
        "coordinates": (
            (
                (xmax, ymax),
                (xmax, ymin),
                (xmin, ymin),
                (xmin, ymax),
                (xmax, ymax),
            ),
        ),
    }
]

# use fit combined with clip=True
base = (
    alt.Chart(data_world)
    .mark_geoshape(clip=True, fill="lightgray", stroke="black", strokeWidth=0.5)
    .project(type="equalEarth", fit=extent)
)

base + wedge
```
image

**Review by joelostblom — COMMENTED** [review]
Awesome! Thanks for also harmonizing the titles, very satisfying =)

> All examples in the "Tables" section, except for maybe the Wind Vector Map, could also be moved into the newly created "Distributions" section (in your issue you mentioned the binned histogram). I'd suggest to do this, what do you think?

Yeah, I see your point. I think we should move the one called "Binned heatmap" and rename it to "2D histogram heatmap". To me the Github Punch card is also a distribution chart (a categorical 2D histogram). I also agree with Mattijn that the wind vector one is better in the maps section after his modification.

That doesn't leave to many table based plots, but for the heatmap with text, we could keep it in the table section but make it based on this VL example instead https://vega.github.io/vega-lite/examples/rect_heatmap.html, so that it does not show a count but the mean instead. And maybe we could also add the weather and lasagna heatmaps from the VegaLite gallery (the mosaic chart also looks cool, but time consuming to make)?

- https://vega.github.io/vega-lite/examples/rect_lasagna.html
- https://vega.github.io/vega-lite/examples/rect_heatmap_weather.html

> As discussed, I rewrote the Strip Plot with Jitter example using the new offset encoding. However, it's now almost the same as Jitter Chart which has a better description. What about removing Jitter Chart and adding the reasoning of why using jitter to the "Strip Plot with Jitter" chart?

Yes, I am good with this too. I also added a suggestion for including both uniform and gaussian jitter.

> The category "Other Charts" is currently empty but shows up at the bottom of the gallery. Ok if I remove it? I saw that it is used as a fallback category for unclassified examples but we could also just raise an error or warning if this happens.

Yes, I think this is a better approach so feel free to add a warning or even raise an error if an example does not include a category so that we notice it right away.

**Comment by binste** [comment]
Thank you both for the great inputs! I addressed them all, including the Mosaic plot :), in the latest push and updated the documentation at https://binste.github.io/altair-docs/gallery/index.html

**Review by joelostblom — APPROVED** [review]
This looks fantastic! Thanks for all the additional work in adding the new examples, really neat =)

**Pull request merged**
