### PR TITLE
doc format  #935 

### LINKED ISSUE #935: Doc on altair.Scale format broken
https://altair-viz.github.io/user_guide/API.html?highlight=scale#altair.Scale
image

### PR DESCRIPTION
**Pull request by iliatimofeev**
fix #935 doc format
*  **Key issues**
   1. Rich link format in vega-lite schema descriptions 
    2. Multiple paragraphs and list items in description 
*  **Affected components**
   1. `.. altair-object-table::` directive
   2.  API Reference generated from schema wrappers docstrings
*  **Results**
   1.  see it on [my temporal fork](https://iliatimofeev.github.io/altair-viz.github.io/) 
   2.  images
## Key issues
Schema descriptions have rich `markdown` format that difficult to translate into `rst` format of `Altair` documentation. 
#### 1. Rich link format in vega-lite schema descriptions 
According to vega-lite contributing guidelines
~~~markdown
- Wrap properties (`key`) with back ticks.
- Wrap values with back ticks for numbers and booleans (e.g., `5`, `true`) 
and wrap string values with both back ticks and double quotes (`"red"`).
~~~
I count not find any reStructuredText syntax to express that  formatting in link declaration.  

#### 2. Multiple paragraphs and list items in description 
From vega-lite [scale.html#range](https://vega.github.io/vega-lite/docs/scale.html#range)
image

#### 1. `.. altair-object-table::` directive 
Generates tables from descriptions in user guide part of documentation. Updated in https://github.com/altair-viz/altair/pull/1037/commits/1157b7e329162265a10978006c5ee31feee9f47b

New version generates tables directly as `docutils.nodes` tree and uses recommended by `Sphinx` `recommonmark` parser for description string parsing.
#### 2.  API Reference generated from schema wrappers docstrings
`SchemaGenerator` and `CodeSnippet` and `indent_docstring` generates docstrings from schema descriptions. Updated in https://github.com/altair-viz/altair/pull/1037/commits/d302c374402c81d4b79d837455ba0a25492ca180
New version removes incompatible formatting from link definitions. Splits description strings into lines and preserves correct indentation for lists while wrapping text into docstring.    
## Results
Tested and build with 
~~~
Sphinx 1.7.5 
sphinx-rtd-theme 0.4.0
recommonmark 0.4.0
~~~

#### New `altair-object-table`
from [encoding.html#encoding-channel-options](https://iliatimofeev.github.io/altair-viz.github.io/user_guide/encoding.html#encoding-channel-options)
image
#### New API Reference 
from [API.html#altair.LayerChart](https://altair-viz.github.io/user_guide/API.html#altair.LayerChart)
image **Note:** `Sphinx 1.7.5` do not show table of attributes (it is a table but  css settings from template hides it) I've tested it with simple docstrings it always looks this way.

### CODE REVIEW

**Comment by jakevdp** [comment]
Thanks for tackling this – I'm going to fork and build the docs locally, since we don't have docs as part of CI at the moment.

**Comment by jakevdp** [comment]
Update... it actually does work with sphinx 1.6.3 and sphinx 1.7.6... turned out I downloaded your branch but didn't check it out 😆 

Thanks so much for this contribution! It really makes the docs easier to read & understand.

**Comment by iliatimofeev** [comment]
What do you think on including semi automatic importing (adopting) vega-lite documentation? It could be done with some efforts. I did some prototyping while working on this issue, it is harder than I expected but still could be done. So it could close questions which are documented in vega-lite but not on altair.

**Comment by iliatimofeev** [comment]
Yes but all links now directed to vega-lite documentation. So you need to read vega-lite documentation then check how it could be represented by Altair. We can update links to Altair object while parsing but I'm not sure that Schema description in API is enough to use it .

**Pull request merged**
