### PR TITLE
Type hints: Finish type hints and mark package as typed

### LINKED ISSUE #2951: Type hints: Summary issue
Currently, Altair only has a few type hints to help IDEs provide better autocompletion suggestions. More type hints would further help IDEs provide a better development experience as well as static type checkers to catch potential errors before they appear at runtime. Especially applications (e.g. a company-internal web application) and frameworks (e.g. Streamlit, Great Expectations) which want to tightly integrate with Altair could greatly profit from this.

I'd suggest the following approach for Altair which is in line with [Using mypy with an existing codebase](https://mypy.readthedocs.io/en/stable/existing_code.html). Very open for inputs!

## Should happen before the v5 release
- [x] https://github.com/altair-viz/altair/pull/2949 Improvements in here could wait until after v5 but it also fixes some wrong type hints

## v5 or minor release
I think it's preferable to have the following items more or less bundled into one release from which on Altair is declared as a library supporting type checks. This could be a minor release (5.1?) as it should not affect any runtime behaviour. Goal is to have as much as possible of the "public API" of Altair typed and then incrementally do the rest later on if we see value in it.

- [x] https://github.com/altair-viz/altair/pull/2950 after #2949 is merged. This is a prerequisite for the following tasks so that mypy can tell us if the type hints are reasonable. We're in a fortunate position that we have many example charts in the `tests` folder which mypy can use for this.
- [ ] With mypy added in the previous step, we should aim to type as much as possible of the "public API" of Altair so users can get the most benefit out of this exercise. "internal" code can follow later. How about the following prioritization:
  - [x] `schemapi.py`: #3142
  - [x] `altair/vegalite/v5/api.py`: #3143
  - [x] Parts of folders "vegalite", "v5", and "utils": #2976
  - [ ] For the autogenerated files, we should infer types from the VL schema, see https://github.com/altair-viz/altair/issues/2854: #3208
  - [x] Remaining files in utils: mimebundle.py, save.py: #3248 
  - [ ] Finishing touches #3263 
    - [x]  Type hint `Undefined` as `UndefinedType`. Search for `# Remove "ignore" statement once Undefined is no longer typed as Any` in code which was introduced in #2950 to make mypy pass.
    - [x] Go through current code and search for `# type: ignore` and see if any of those mentions can now be removed or better type hinted
    - [x] Some types might still be marked as private as they start with an `_`. Search for `_[A-Z]` to find them and convert to public types if they are used in public parts of the codebase. This way, others can use the types themselves for code that depends on Altair. This was discussed [in this issue](https://github.com/altair-viz/altair/pull/3081#issuecomment-1587319604).
      - [x] Do we need better naming conventions for these types? Are the names clearly representing the intention/meaning of the types?
    - [x] Declare Altair a library which supports type hints (probably by adding `py.typed`) as mentioned in [the mypy docs](https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages) (also note the mention of `zip_safe` and including the file in wheels and sdist, test this) → This allows mypy to use it when imported in other projects. Once https://github.com/microsoft/pylance-release/issues/4059 is fixed we can also finish https://github.com/altair-viz/altair/pull/2927

## After release of the above
- [ ] Remove exclusion of Altair in mypy.ini files in altair_viewer and altair_saver
 
@mattijn @joelostblom Would you be open to this? Input on the release cycle? I could review PRs related to this topic and create some myself.

### PR DESCRIPTION
**Pull request by binste**
This will close #2951  🥳 

- [x] Build wheel file and test it on a larger Altair code base

### CODE REVIEW

**Comment by mattijn** [comment]
Thanks @binste! Can you briefly explain how these new public types can be used from outside Altair? Would it be possible to import certain types from Altair and do some checks without defining a `Chart` object?

**Comment by binste** [comment]
Sure! For example, if you have a function which creates a chart object based on some inputs, it would be great to make sure to test that the passed in data is something that Altair can deal with:

```python
import pandas as pd
import altair as alt


def make_line_chart(data: alt.ChartDataType, x: str, y: str) -> alt.Chart:
    # Imagine that this function creates a more complicated chart spec
    return alt.Chart(data).mark_line().encode(x=x, y=y)


make_line_chart(data=pd.DataFrame(), x="a", y="b")  # This passes
make_line_chart(
    data=2, x="a", y="b"
)  # error: Argument "data" to "make_line_chart" has incompatible type "int"; expected "dict[Any, Any] | DataFrame | _SupportsGeoInterface | _DataFrameLike | Data | str | Generator | UndefinedType"  [arg-type]
```

For most users, these types/type aliases are probably irrelevant but if you build an application or framework which wants to tightly integrate with Altair, I think they can come in handy.

**Comment by mattijn** [comment]
Thanks! Shall we make `_SupportsGeoInterface` and `_DataFrameLike` public too? Seems useful.

**Review by jonmmease — COMMENTED** [review]
> Thanks! Shall we make _SupportsGeoInterface and _DataFrameLike public too? Seems useful.

I agree. I think `_DataFrameLike` should be public since it's the return type of `chart.transformed_data()`. We expose `_SupportsGeoInterface` as part of the `Union` defining the public `DataType` type, so I think it should be public as well.

**Comment by binste** [comment]
Fully agree, thanks for catching that.

**Comment by mattijn** [comment]
Nice! One more question, what is the difference between `ChartDataType` and `DataType`?

**Comment by mattijn** [comment]
I see already:

```python
DataType = Union[dict, pd.DataFrame, SupportsGeoInterface, DataFrameLike]

ChartDataType = Union[DataType, core.Data, str, core.Generator, UndefinedType]
```

`DataType` is a subset of `ChartDataType`

**Review by mattijn — APPROVED** [review]
Congrats @binste! A lot of hard work! Thanks. Let's start testing this within real use cases in the coming period.

**Comment by binste** [comment]
Thanks! Yeah it was a longer journey but also very educational for me and I hope it's of use. I already tested it on a medium-sized web application which uses many Altair charts and it allowed me to discover some edge cases in the application code which could have led to bugs :)

**Pull request merged**
