### PR TITLE
Added layered heatmap + text example

### PR DESCRIPTION
**Pull request by seeM**
Tried to reproduce [this](https://vega.github.io/vega-lite/examples/layer_text_heatmap.html) plot from the vega docs. No idea how to do the final step, which is to change the text color of those rectangles with values greater than 100 to black.

plot

### CODE REVIEW

**Comment by jakevdp** [comment]
Very nice! The conditional color will be possible once #463 is finalized and merged. It will look something like this:

```
encode(
    ...
    color=alt.condition("datum['count_*'] > 100", alt.ColorValue('white'), alt.ColorVaue('black'))
)
```

though that API is not finalized

**Comment by jakevdp** [comment]
I'll hold off on merging this until the ``condition`` API is merged.

**Comment by jakevdp** [comment]
OK, the condition API is in master now! With it, the chart can be created this way:
```python
import altair as alt
from vega_datasets import data

cars = data.cars.url

heatmap = alt.Chart(cars).mark_rect().encode(
    alt.X('Cylinders:O', scale=alt.Scale(paddingInner=0)),
    alt.Y('Origin:O', scale=alt.Scale(paddingInner=0)),
    alt.Color('count(*):Q')
)

text = alt.Chart(cars).mark_text(
    baseline = 'middle'
).encode(
    alt.X('Cylinders:O'),
    alt.Y('Origin:O'),
    alt.Text('count(*):Q'),
    color=alt.condition("datum['count_*'] > 100",
                        alt.ColorValue('black'),
                        alt.ColorValue('white'))
)

chart = heatmap + text
```
vega 9

**Comment by seeM** [comment]
Yeah, so... I'm in dire need of assistance here :'D

I was just trying to keep my branch up-to-date with the original, but ended up doing all sorts of weird things.

Will it just be easier to delete this branch and create a new one?

**Comment by seeM** [comment]
I've commited the suggested change, though when attempting to run it myself I get a NotImplemented error:
```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-6-0c320424de4f> in <module>()
     25     color=alt.condition("datum['count_*'] > 100",
     26                         alt.ColorValue('black'),
---> 27                         alt.ColorValue('white'))
     28 )
     29 

~\GitHub\altair\altair\vegalite\v2\api.py in condition(predicate, if_true, if_false)
    128     else:
    129         raise NotImplementedError("condition predicate of type {0}"
--> 130                                   "".format(type(predicate)))
    131 
    132 

NotImplementedError: condition predicate of type <class 'str'>
```

**Comment by jakevdp** [comment]
Sorry, I forgot to push my changes to master before I went to bed last night :smile:

It's there now... I'll restart the test and hopefully this will work

**Comment by jakevdp** [comment]
Alright, it's working now! Thanks for the contribution

**Pull request merged**
