### PR TITLE
Add US state capitals from vega-lite.

### PR DESCRIPTION
**Pull request by lawlesst**
See also pull request [#5 to vega_datasets](https://github.com/jakevdp/vega_datasets/pull/5) to add the state capitals. 

Please let me know if anything should be adjusted.

### CODE REVIEW

**Comment by jakevdp** [comment]
It looks like the us_state_capitols data hasn't made it into the ``vega_datasets`` release yet. I'll try to do that soon, and then this example should work properly

**Comment by afonit** [comment]
@jakevdp will that update to vega_datasets also include the disasters dataset?
https://vega.github.io/vega-lite/examples/circle_natural_disasters.html

**Comment by jakevdp** [comment]
@afonit yes, it's already in the master branch! I'll try to do a release tonight when I have a bit more time :smile:

**Comment by jakevdp** [comment]
the data is now in the vega_datasets 0.4 release!

This is a nice example; I think a useful tweak would be to also show the capital locations as points on the map. Something like this:
```python
import altair as alt
from vega_datasets import data

states = alt.UrlData(data.us_10m.url,
                     format=alt.TopoDataFormat(type='topojson',
                                               feature='states'))
capitals = data.us_state_capitals.url

# US states background
background = alt.Chart(states).mark_geoshape(
    fill='lightgray',
    stroke='white'
).properties(
    projection={'type': 'albersUsa'},
    width=800,
    height=500
)

# State capitals labeled on background
points = alt.Chart(capitals).mark_text(dy=-5, align='right').encode(
    alt.Text('city', type='nominal'),
    alt.X('lon', type='longitude'),
    alt.Y('lat', type='latitude'),
)

chart = background + points + points.mark_point(color='black')
```
vega 7

**Comment by jakevdp** [comment]
Looks good, thanks!

**Comment by lawlesst** [comment]
Great. Thanks for reviewing and the example of using points to mark the location.

**Pull request merged**
