### PR TITLE
Inject empty data at top level for easier datum encodings

### PR DESCRIPTION
**Pull request by jakevdp**
.cc @mattijn 

I think this is roughly what you had in mind in the previous discussion (https://github.com/altair-viz/altair/pull/2513#issuecomment-960643083). We may want a more sophisticated version of this rather than *always* adding empty data at the top level.

### CODE REVIEW

**Comment by ChristopherDavisUCI** [comment]
I saw in the Vega-Lite schema that "type": "null" is an allowable option for the `data` property.  Is there a standard way to use that in Altair?  For me writing something like `alt.Chart(None)` is just as nice (or maybe even nicer since it's more explicit) as writing `alt.Chart()` if we want to specify empty data.

**Comment by jakevdp** [comment]
Interesting - where do you see that `{"type": null}` is a valid option for data? When I look at the schema, I only see URLData (which requires `"url"`), NamedData (which requires `"name"`), and InlineData (which requires `"values"`)

**Comment by ChristopherDavisUCI** [comment]
Maybe you're one level deeper in the schema than I am?  I see `"type": "null"` under:
`TopLevelUnitSpec->properties->data`.

**Comment by jakevdp** [comment]
Ah, yeah I see. I think the meaning of `data=None` is different than what we want here, though:
```
"description": "An object describing the data source. Set to `null` to ignore the parent's data source. If no data is set, it is derived from the parent."
```

**Comment by ChristopherDavisUCI** [comment]
I see!  I often find those schema descriptions difficult to parse, so I've often gotten in the habit of not even looking at them.

If there's anything you'd like me to try related to this empty encoding, just let me know (I couldn't tell if there was more to be done or not).  But for now I'll go back to thinking about version 5.

**Comment by mattijn** [comment]
I played a bit with this; I think it works good.

**Pull request merged**
