### PR TITLE
ENH: track JS versions in default HTML display

### PR DESCRIPTION
**Pull request by jakevdp**
Tested in Chrome & Safari, with JupyterLab, Jupyter Notebook, and Colab frontends.

cc/ @mattijn

### CODE REVIEW

**Comment by mattijn** [comment]
I don't see continuous script injection the html DOM, which is a good thing. 

Using MS Edge I can reproduce the effect that my mem/cpu goes high. This happens when a console log window is opened and holding ctrl+enter on an Altair charting cell. Eventually  the console log window crash and then my mem/cpu is stable again. This also can be reproduced with Altair v4.1.0 installed. This only happens in MS Edge; Chrome stays stable with the console log window open.

**Comment by jakevdp** [comment]
Just to be clear - the console log crash on Edge happens with the current release, not just with this change?

**Comment by mattijn** [comment]
Yes. Not related to this PR.

**Comment by mattijn** [comment]
I thought maybe its tracking all unique added `divs` under the hood in the console log somewhere. But I cannot make it to crash anymore and now it runs stable in Edge too. Also I do not observe any tracking of previously rendered Altair charts. So probably an incident then.

**Comment by jakevdp** [comment]
Seems like this is working as intended, and we haven't encountered any issues yet. I'm going to merge.

**Comment by mattijn** [comment]
Good. Only one comment I want to add. It's not specific about this PR, but I was wondering for a certain scenario: In a Jupyter session, after upgrading Altair, the newest vega lite version is injected and used for rendering. If a person decide to switch back to a previous altair version, than the previous schema is used to validate against, but still the newest vega lite package is used for rendering. Can this result to some cases where the chart won't render due to breaking changes in higher versions of vega-lite?

**Comment by jakevdp** [comment]
vega-lite.js tends to be mostly backward-compatible even for attributes that are no longer part of the schema (for example, vega-lite 5 still will correctly render most if not all vega-lite 4 specifications, though it will display console warnings about deprecated entries). So I expect if you are mixing Altair 4.1 & 4.2 charts in a single Jupyter JS session, after this change they should render fine no matter which version you display first.

**Comment by mattijn** [comment]
Great, looking forward!

**Pull request merged**
