### PR TITLE
DOC: add scatter with loess example

### PR DESCRIPTION
**Pull request by eitanlees**
visualization (50)

I thought an example of adding multiple grouped LOESS lines to a scatter plot could be a useful addition to the docs.

### CODE REVIEW

**Comment by jakevdp** [comment]
Nice example! What would you think about replacing the ``melt()`` operation with a fold transform?

**Comment by eitanlees** [comment]
Sure thing. I based this example on [Multi-Line Tooltip](https://altair-viz.github.io/gallery/multiline_tooltip.html) which used `melt()`.

Now that the transforms have improved some of the examples are outdated in subtle ways. In general do we want to use built in transforms?

**Comment by jakevdp** [comment]
>  In general do we want to use built in transforms?

Good question... thinking about it, I'd say we should use built-in transforms whenever they make the examples clearer. I think the fold transform here is a bit clearer than ``pd.melt``; I also think that ``reset_index()`` here is probably clearer than using ``transform_window(x='count()')``.

**Comment by eitanlees** [comment]
Personally I like the example given from the [Fold Transform](https://altair-viz.github.io/user_guide/transform/fold.html#user-guide-fold-transform) page where the data is intialized as such. 

```python
import numpy as np
import pandas as pd
import altair as alt

rand = np.random.RandomState(0)
data = pd.DataFrame({
    'date': pd.date_range('2019-01-01', freq='D', periods=30),
    'A': rand.randn(30).cumsum(),
    'B': rand.randn(30).cumsum(),
    'C': rand.randn(30).cumsum(),
})

alt.Chart(data).transform_fold(
    ['A', 'B', 'C'],
).mark_line().encode(
    x='date:T',
    y='value:Q',
    color='key:N'
)
```

I feel this is a nice way to build a toy dataframe that doesn't need any index resetting. If you agree I can change this example to have that form.

**Comment by eitanlees** [comment]
Maybe I should revisit the idea of an Altair examples style guide.

**Comment by jakevdp** [comment]
Yeah, that looks great: everything is very explicit and understandable, even to a reader who's not very familiar with pandas.

Would you be willing to update this PR with that style?

**Comment by eitanlees** [comment]
Absolutely! I think this example is good to go! 

visualization (51)

**Comment by jakevdp** [comment]
Thanks!

**Pull request merged**
