### PR TITLE
Fix the test notebooks

### PR DESCRIPTION
**Pull request by domoritz**
The notebooks were using an undefined `vegalite` property. The Vega-Lite 1 notebook used the v2 api.

### CODE REVIEW

**Comment by domoritz** [comment]
Unfortunately, I could not render some of the older charts. I'll try again with https://github.com/jupyterlab/jupyter-renderers installed.

**Comment by domoritz** [comment]
I'm stuck at https://github.com/jupyterlab/jupyter-renderers/issues/167. Can you rerun the notebooks for me?

**Comment by domoritz** [comment]
I fixed them but there is a JS error in VL 1. Not sure what's the problem.

**Comment by jakevdp** [comment]
I'd honestly be fine removing these notebooks if they're causing a problem. They're not part of any automated tests, and are of little value as documentation.

**Comment by domoritz** [comment]
I deleted them. I think it's still good to have a separate commit with the fixed notebooks as the last commit before they get deleted.

**Comment by jakevdp** [comment]
OK, thanks!

**Pull request merged**
