### PR TITLE
BUG: changing eps to svg for save filetypes

### PR DESCRIPTION
**Pull request by jowens**
Per @jakevdp's request, to fix when he types 'eps' instead of 'svg'. 'eps' is removed with this pull request and replaced with 'svg'.

Fixes https://github.com/altair-viz/altair/issues/722 . Categorized as a bug because 'svg' wouldn't have worked.

### CODE REVIEW

**Comment by jakevdp** [comment]
Every mention of eps was in a doc string or an error message, so this is not a bug, just a typo.

**Comment by jakevdp** [comment]
Looks like maybe your editor has some auto-formatting built-in?

**Comment by jowens** [comment]
pep8 compliance, yes. Want me to try again without that?

**Comment by jakevdp** [comment]
Maybe... it's a bit confusing to have so many changes associated with an unrelated commit message.

**Comment by jowens** [comment]
OK. Will get back to this later tonight. Sorry!

**Pull request closed without merging**
