### PR TITLE
Fix contributing descriptions

### PR DESCRIPTION
**Pull request by thomend**
This PR will resolve https://github.com/altair-viz/altair/issues/3014

### CODE REVIEW

**Comment by joelostblom** [comment]
Thanks for the update, I would be OK merging this as is without adding guidelines for two dataframes

**Comment by binste** [comment]
Thanks @thomend! How about adding something like "If the example requires multiple dataframes then this does not apply." at the end of the bullet point which mentions 'sources'? On mobile right now so I cant link to the exact location.

**Comment by thomend** [comment]
> Thanks @thomend! How about adding something like "If the example requires multiple dataframes then this does not apply." at the end of the bullet point which mentions 'sources'? On mobile right now so I cant link to the exact location.

Thanks for the input, @binste, I added this in the contributing guidelines and marked the PR as ready for review.

**Review by binste — APPROVED** [review]
Looks good, thanks @thomend!

**Pull request merged**
