### PR TITLE
Added g3o2's Dot-Dash Plot Example

### PR DESCRIPTION
**Pull request by eitanlees**

### CODE REVIEW

**Comment by afonit** [comment]
@eitanlees ,
It says I can't edit your branch, but just adding this comment as I saw the request for all examples to have .url and typed:

"""
Dot Dash Plot
=============
This example shows how to make a dot-dash plot presented in Edward Tufte's book Visual Display of Quantitative Information on page 133. This example is based on g3o2’s Block bd4362574137061c243a2994ba648fb8
"""

import altair as alt
from vega_datasets import data

cars = data.cars.url

points = alt.Chart(cars).mark_point().encode(
    x=alt.X('Miles_per_Gallon:Q',axis=alt.Axis(title='')), 
    y=alt.Y('Horsepower:Q',axis=alt.Axis(title='')), 
    color='Origin:N'
)

x_ticks = alt.Chart(cars).mark_tick().encode(
    x=alt.X('Miles_per_Gallon:Q',axis=alt.Axis(labels=False, 
                                             domain=False, 
                                             ticks=False)), 
    y=alt.Y('Origin:N',axis=alt.Axis(labels=False, 
                                   domain=False, 
                                   ticks=False,
                                   title='')), 
    color='Origin:N'
)

y_ticks = alt.Chart(cars).mark_tick().encode(
    y=alt.Y('Horsepower:Q',axis=alt.Axis(labels=False, 
                                       domain=False,
                                       ticks=False)), 
    x=alt.X('Origin:N',axis=alt.Axis(labels=False, 
                                   domain=False, 
                                   ticks=False,
                                   title='')), 
    color='Origin:N'
)

chart = alt.hconcat(y_ticks, alt.vconcat(points, x_ticks))

**Comment by eitanlees** [comment]
It’s not all examples. Only examples that use non local data from the Vega datasets package.

**Comment by afonit** [comment]
@eitanlees got it - thanks

**Comment by jakevdp** [comment]
Ha, I was just writing a comment saying you should try adding a brush :smile:

**Comment by jakevdp** [comment]
This looks really great, by the way!

**Pull request merged**
