### PR TITLE
docs: examples: add line plot with custom order

### PR DESCRIPTION
**Pull request by NickCrews**
Followup to https://github.com/altair-viz/altair/pull/3155.

I think this use case should be more easily discoverable, so it should be in the example gallery. Let me know if I need to do something else, or if just creating this file will trigger discovery and build.

I tweaked the prose from https://altair-viz.github.io/user_guide/marks/line.html#connected-scatter-plot-line-chart-with-custom-path just a little bit

### CODE REVIEW

**Comment by mattijn** [comment]
Thanks for this PR @NickCrews! Make sense to surface this a bit more in the example gallery.

But Altair specifications for the example gallery require a tiny bit more effort. Namely, every example should have an `arguments_syntax` and `methods_syntax` implementation. Each implementation must be saved as a stand alone script in the `tests/examples_arguments_syntax` and `tests/examples_methods_syntax` directories.

Currently you have added the Altair specification using a `methods_syntax` to the `examples_arguments_syntax` folder. 

Hopefully this is clear enough to make the additional changes. Thanks again for the PR!

**Comment by NickCrews** [comment]
Thanks for the explanation! Is that correct now?

**Comment by NickCrews** [comment]
PS, in a followup commit should I reverse the x and y on all of these charts? Seems like gas price is the more logical independent variable, and miles driven is the dependent.

**Comment by mattijn** [comment]
Looks good now, regarding syntax. Thanks for the follow-up!

Regarding changing `x`/`y` order. It  would be good to do this in a separate PR. Also, for that change I would like to have an approval of another maintainer. 

Thanks again for this PR!

**Review by mattijn — APPROVED** [review]

**Comment by NickCrews** [comment]
Oh wait 🤦 this is already present as a scatter plot example at https://altair-viz.github.io/gallery/connected_scatterplot.html.

I would vote to remove that one, and keep this one. This is more of a line plot, since we use mark_line(), and the connectivity of the points is significant.

**Comment by mattijn** [comment]
No problem. I agree with you that it make more sense to place it in the line chart section. Can you make the change (in a new PR as this PR is merged already).

**Pull request merged**
