### PR TITLE
added the streamgraph example from vega-lite

### PR DESCRIPTION
**Pull request by afonit**
Everything is working except turning off the y-axis.

In the vega-lite json it says:
"axis": null

I have tried:
axis = False
and
axis = 'null

neither have worked.

### CODE REVIEW

**Comment by jakevdp** [comment]
use ``axis=None``. It's the convention used within the ``json`` package that python ``None`` becomes Javascript ``null``.

**Comment by hydrosquall** [comment]
Minor typo in the filename, I think you might mean `streamgraph`

**Comment by afonit** [comment]
@hydrosquall, yes you are correct, thanks for the catch

**Comment by jakevdp** [comment]
Thanks!

**Pull request merged**
