### PR TITLE
ENH: interactive widget to plot different columns (WIP)

### PR DESCRIPTION
**Pull request by stsievert**
Adds `altair.utils.interact_with` that allows functionality to plot different columns:

untitled-3

This depends on ipywidgets.interact. I see there's some work on using the branch altair#widget (not my branch). In my implementation, I have dropdown menus for the type of mark (line, point, area, etc) and the different encodings (x, y, color, etc).

There's a ton of work to do still:

* tests, documentation
* support for different stats function (median, max, mean, etc)
* style dropdown menus
* ensure works for heat maps (for my use case this will require `applyColorToBackground`). This will likely require styling the drop downs.

### CODE REVIEW

**Comment by jakevdp** [comment]
This is pretty cool! One note: what you're doing here is quite similar to the voyager 2 JS frontend that the Vega-Lite team are developing; see a demo at https://uwdata.github.io/voyager2/

Long-term I'd love to enable seamless two-way interaction between Altair and Voyager2 within JupyterLab. With that in mind, we'll have to think carefully about whether we want to duplicate that type of functionality at the ipywidget level as well. An enhancement like the one you show here would lead to a non-negligible maintenance cost in the long-term, which is an important consideration.

**Comment by stsievert** [comment]
Interesting -- thanks for showing! Voyager 2 has a better user interface  -- has more clear how Vega works and better dashboard interface to select functions.

However, right now I do prefer the ipywidgets implementation slightly. I like the immediate showing of results by selecting from a drop-down menu, instead of clicking and dragging (which feels like more work).

> a non-negligible maintenance cost in the long-term

I had the same thought. Maybe we should add to the docs instead? We can mention Voyager 2 as the upcoming software then mention that if a basic and immediate implementation needed, use the function implemented here.

**Comment by jakevdp** [comment]
> Maybe we should add to the docs instead?

How would you feel about putting this widget interface under a separate package in the altair-viz org? perhaps altair-viz/altair_widgets? I'd love to see this developed more, and a separate package would allow more flexibility in that.

**Comment by stsievert** [comment]
Perfect! I've published this with the same license as altair at https://github.com/stsievert/altair_widgets. I've added you as a collaborator so you can transfer the repo into altair-viz.

I've also added support for row and column.

**Comment by stsievert** [comment]
I've added a better interfacing option.

car_example

**Comment by jakevdp** [comment]
I think only the repo owner can transfer... I've added you as a member of altair-viz, so I think you can do it now.

**Comment by stsievert** [comment]
Repo transferred. It's only possible to transfer repos to organizations you have admin rights to :/. But I'm comfortable closing this PR now.

I have put more work into better styling the menu (the current toolbar is below). I have run into a fairly small issue, and can resolve it by putting more effort into tests and simplifying the code.

screen shot 2016-10-29 at 3 01 33 pm

**Pull request closed without merging**
