### PR TITLE
DOC: Example gallery reorganization

### PR DESCRIPTION
**Pull request by palewire**
Replaces #788 (where you can find a fuller discussion). For #775.

### CODE REVIEW

**Comment by kanitw** [comment]
FYI, we're now also [restructuring the Vega-Lite gallery](https://github.com/vega/vega-lite/pull/3679#pullrequestreview-116151298) -- obviously motivated by this change here.  :)

**Comment by jakevdp** [comment]
I finally had a chance to download and build this... looks really good!

I wonder if it wouldn't be worth adding a half dozen more simple charts for the first category. At the very least we should demo various marks that are available.

**Comment by jakevdp** [comment]
I'm going to go ahead and merge this, and then separately add a few more examples to the "Simple" category.

**Comment by palewire** [comment]
I agree that adding more simple charts would be good.

One idea: Each subsection has a corresponding simple chart.

**Pull request merged**
