### PR TITLE
ENH: add binding interface

### PR DESCRIPTION
**Pull request by jakevdp**
Add a Python interface to bindings, plus an example:
ezgif-5-9d02b5a3cc

### CODE REVIEW

**Comment by eitanlees** [comment]
I have a question. Each time we add an example could it affect the indices that are used to populate the docs homepage?

**Comment by jakevdp** [comment]
Yes, at the moment that's the case. I'd like to change it so that it uses filenames rather than indices.

**Comment by jakevdp** [comment]
Actually, what I'd really like is to change the ``mini-gallery`` extension so that it outputs a more dynamic gallery, similar to the top of the vega-lite page: https://vega.github.io/vega-lite/

**Comment by jakevdp** [comment]
I'm going to merge this... I think it's all set.

**Pull request merged**
