### PR TITLE
Use HTTPS prefix in example URLs to fix CORS issue

### PR DESCRIPTION
**Pull request by cmsetzer**
Per issue #407, a few examples in the documentation have HTTP-prefixed URLs that result in CORS errors when using Altair in Jupyter Notebook. This commit updates the default URL prefix in the example-syncing functions to `https://`, which should resolve the CORS issue when the examples are synced and the docs are re-built.

@jakevdp, want to take a look at this when you get a chance?

### CODE REVIEW

**Comment by ellisonbg** [comment]
Have you tested this to make sure it works from notebooks running themselves on both http and https domains?

**Comment by jakevdp** [comment]
For this to change the urls in the package, you'll have to run ``python tools/sync_vegalite_examples.py`` and then commit the updated files.

**Comment by cmsetzer** [comment]
@ellisonbg, good question. After serving notebooks locally via HTTP and HTTPS (per [these docs](http://jupyter-notebook.readthedocs.io/en/stable/public_server.html#using-ssl-for-encrypted-communication)) I don't believe this is an issue. Either way, rendering an Altair Chart from e.g. `http://vega.github.io/vega-lite/data/population.json` fails with a CORS error while the same URL prefixed with `https://` succeeds. (Feel free to correct me if I've misunderstood.)

@jakevdp, I've just run `sync_vegalite_examples.py` and pushed the updated JSON files.

**Comment by jakevdp** [comment]
I can't think of any side-effects for this... I'm going to merge. Thanks!

**Pull request merged**
