### PR TITLE
DOC: Standardized grouped bar chart example

### PR DESCRIPTION
**Pull request by palewire**
* Substituted dataset common to bar examples
* Reduced code complexity
* Fixed "too wide" bug
* Added more docs
* Added second horizontal version of the example

### CODE REVIEW

**Comment by palewire** [comment]
Looks like @eitanlees and I were on the same page today. I noticed #1238 after I filed the PR. I think mine still should be considered as an addendum, though he clearly beat me to the punch.

**Comment by jakevdp** [comment]
Thanks for looking at this – I think I'd prefer to have a minimal grouped bar chart example that doesn't require any data transforms: it's a common enough question that I'd like to have a bare-bones example like the one added in #1238.

**Comment by palewire** [comment]
Fair. I still think it's worth adding a companion version that runs on the other axis as well as the inline comments I've put in. Let me loop back and make another run at this patch.

**Comment by palewire** [comment]
My revisions are in. Let me know what you think.

**Comment by jakevdp** [comment]
Looks good, thanks!

**Pull request merged**
