### PR TITLE
ENH: make vega_datasets accessible from alt.datasets

### PR DESCRIPTION
**Pull request by jakevdp**
Addresses #796

This makes the contents of ``vega_datasets`` available from Altair via ``alt.datasets``. So, for example, you can do:
```python
import altair as alt
cars = alt.datasets.cars()
alt.Chart(cars).mark_point()
```

If the vega_datasets package is not installed,  an error will be raised when you try to access a dataset, but not when you import the ``alt.datasets`` object (which is present in the main namespace)
```pytb
In [1]: from altair import datasets
In [2]: datasets.cars()
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-a4a02b6877f0> in <module>()
----> 1 datasets.cars()

~/github/altair-viz/altair/altair/_datasets.py in __getattr__(self, attr)
     21 
     22     def __getattr__(self, attr):
---> 23         raise ImportError(ERR_MESSAGE)
     24 
     25 

ImportError: 
The vega_datasets package must be installed in order to use altair.datasets.
See http://github.com/altair-viz/vega_datasets/ for information.
```

### CODE REVIEW

**Comment by jakevdp** [comment]
I'm still about 50/50 on this change... or maybe 60/40 in favor.

- Pros
  - fewer imports leads to simpler examples and an easier learning curve for beginners
  - there is still no hard dependency on vega_datasets, so Altair can be used without it
  - this will open the way for more streamlined tools for things like choropleth maps, which require access to the data

- Cons
  - this obscures the existence of the vega_datasets package and might make it less clear how to debug issues that arise, particularly for beginners

**Comment by arokem** [comment]
You might want to also mention somewhere in the documentation (in case that's not already mentioned) that for these data to be available, users should install `vega_datasets` as well.

On the other hand If you don't, users will get that message on the first time they refer to `alt.datasets` so meh.

**Comment by jakevdp** [comment]
All the installation instructions list ``vega_datasets``, so I think we have that covered: https://altair-viz.github.io/getting_started/installation.html

**Comment by arokem** [comment]
You're probably right, but to be on the safe side, in case someone shows up in the examples, instead of this page, I would add something like "Some of these examples also require an installation of `vega_datasets` " on this page: https://altair-viz.github.io/gallery/index.html

**Comment by palewire** [comment]
@arokem, we've already done that in #829

**Comment by arokem** [comment]
Whoops. Sorry about the noise!

**Comment by ellisonbg** [comment]
Jake, I am fine either way on this one


-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jakevdp** [comment]
Having slept on this a bit, I think I'd prefer not to wrap datasets into altair.

**Pull request closed without merging**
