### PR TITLE
Improve MaxRowsError

### PR DESCRIPTION
**Pull request by EntilZha**
Stack created with [Sapling]
* __->__ #2783

Improve MaxRowsError

Summary:

I've modified the error message to give a link to the docs and the command listed there.
Most of the time I run into this, I can safely disable it, but its a little inconvenient to search for the command

### CODE REVIEW

**Comment by mattijn** [comment]
Thanks for the PR! I agree that it is a bit hard to find the exact line how to pass the `MaxRowsError`.  There were recently some more changes to the documentation and I'm not exactly sure if your suggestion still match with the main repository, can you verify this?

By the way, what do you mean with 'Stack created with [Sapling]'.

**Comment by binste** [comment]
The suggestion I made matches the master branch :)

**Comment by mattijn** [comment]
Maybe you know it directly @binste, is https://altair-viz.github.io/user_guide/faq.html#maxrowserror-how-can-i-plot-large-datasets still valid in the updated documentation?

**Comment by binste** [comment]
I forgot to submit the review I started so you probably didn't see my suggestion, that's why the confusion.

**Comment by mattijn** [comment]
No problem @binste! Your comments are much appreciated

**Comment by mattijn** [comment]
Superseded by #2840

**Pull request closed without merging**
