### PR TITLE
ADD: Isotype visualization example

### PR DESCRIPTION
**Pull request by pratapvardhan**
Isotype Visualization example. Credits to @chanwutk vega-lite reference.

image

```python
df =  pd.DataFrame([
      {'country': 'Great Britain', 'animal': 'cattle', 'col': 3},
      {'country': 'Great Britain', 'animal': 'cattle', 'col': 2},
      {'country': 'Great Britain', 'animal': 'cattle', 'col': 1},
      {'country': 'Great Britain', 'animal': 'pigs', 'col': 2},
      {'country': 'Great Britain', 'animal': 'pigs', 'col': 1},
      {'country': 'Great Britain', 'animal': 'sheep', 'col': 10},
      {'country': 'Great Britain', 'animal': 'sheep', 'col': 9},
      {'country': 'Great Britain', 'animal': 'sheep', 'col': 8},
      {'country': 'Great Britain', 'animal': 'sheep', 'col': 7},
      {'country': 'Great Britain', 'animal': 'sheep', 'col': 6},
      {'country': 'Great Britain', 'animal': 'sheep', 'col': 5},
      {'country': 'Great Britain', 'animal': 'sheep', 'col': 4},
      {'country': 'Great Britain', 'animal': 'sheep', 'col': 3},
      {'country': 'Great Britain', 'animal': 'sheep', 'col': 2},
      {'country': 'Great Britain', 'animal': 'sheep', 'col': 1},
      {'country': 'United States', 'animal': 'cattle', 'col': 9},
      {'country': 'United States', 'animal': 'cattle', 'col': 8},
      {'country': 'United States', 'animal': 'cattle', 'col': 7},
      {'country': 'United States', 'animal': 'cattle', 'col': 6},
      {'country': 'United States', 'animal': 'cattle', 'col': 5},
      {'country': 'United States', 'animal': 'cattle', 'col': 4},
      {'country': 'United States', 'animal': 'cattle', 'col': 3},
      {'country': 'United States', 'animal': 'cattle', 'col': 2},
      {'country': 'United States', 'animal': 'cattle', 'col': 1},
      {'country': 'United States', 'animal': 'pigs', 'col': 6},
      {'country': 'United States', 'animal': 'pigs', 'col': 5},
      {'country': 'United States', 'animal': 'pigs', 'col': 4},
      {'country': 'United States', 'animal': 'pigs', 'col': 3},
      {'country': 'United States', 'animal': 'pigs', 'col': 2},
      {'country': 'United States', 'animal': 'pigs', 'col': 1},
      {'country': 'United States', 'animal': 'sheep', 'col': 7},
      {'country': 'United States', 'animal': 'sheep', 'col': 6},
      {'country': 'United States', 'animal': 'sheep', 'col': 5},
      {'country': 'United States', 'animal': 'sheep', 'col': 4},
      {'country': 'United States', 'animal': 'sheep', 'col': 3},
      {'country': 'United States', 'animal': 'sheep', 'col': 2},
      {'country': 'United States', 'animal': 'sheep', 'col': 1}
    ])

domains = ['person', 'cattle', 'pigs', 'sheep']

shape_scale = alt.Scale(
    domain=domains,
    range=[
        'M1.7 -1.7h-0.8c0.3 -0.2 0.6 -0.5 0.6 -0.9c0 -0.6 -0.4 -1 -1 -1c-0.6 0 -1 0.4 -1 1c0 0.4 0.2 0.7 0.6 0.9h-0.8c-0.4 0 -0.7 0.3 -0.7 0.6v1.9c0 0.3 0.3 0.6 0.6 0.6h0.2c0 0 0 0.1 0 0.1v1.9c0 0.3 0.2 0.6 0.3 0.6h1.3c0.2 0 0.3 -0.3 0.3 -0.6v-1.8c0 0 0 -0.1 0 -0.1h0.2c0.3 0 0.6 -0.3 0.6 -0.6v-2c0.2 -0.3 -0.1 -0.6 -0.4 -0.6z',
        'M4 -2c0 0 0.9 -0.7 1.1 -0.8c0.1 -0.1 -0.1 0.5 -0.3 0.7c-0.2 0.2 1.1 1.1 1.1 1.2c0 0.2 -0.2 0.8 -0.4 0.7c-0.1 0 -0.8 -0.3 -1.3 -0.2c-0.5 0.1 -1.3 1.6 -1.5 2c-0.3 0.4 -0.6 0.4 -0.6 0.4c0 0.1 0.3 1.7 0.4 1.8c0.1 0.1 -0.4 0.1 -0.5 0c0 0 -0.6 -1.9 -0.6 -1.9c-0.1 0 -0.3 -0.1 -0.3 -0.1c0 0.1 -0.5 1.4 -0.4 1.6c0.1 0.2 0.1 0.3 0.1 0.3c0 0 -0.4 0 -0.4 0c0 0 -0.2 -0.1 -0.1 -0.3c0 -0.2 0.3 -1.7 0.3 -1.7c0 0 -2.8 -0.9 -2.9 -0.8c-0.2 0.1 -0.4 0.6 -0.4 1c0 0.4 0.5 1.9 0.5 1.9l-0.5 0l-0.6 -2l0 -0.6c0 0 -1 0.8 -1 1c0 0.2 -0.2 1.3 -0.2 1.3c0 0 0.3 0.3 0.2 0.3c0 0 -0.5 0 -0.5 0c0 0 -0.2 -0.2 -0.1 -0.4c0 -0.1 0.2 -1.6 0.2 -1.6c0 0 0.5 -0.4 0.5 -0.5c0 -0.1 0 -2.7 -0.2 -2.7c-0.1 0 -0.4 2 -0.4 2c0 0 0 0.2 -0.2 0.5c-0.1 0.4 -0.2 1.1 -0.2 1.1c0 0 -0.2 -0.1 -0.2 -0.2c0 -0.1 -0.1 -0.7 0 -0.7c0.1 -0.1 0.3 -0.8 0.4 -1.4c0 -0.6 0.2 -1.3 0.4 -1.5c0.1 -0.2 0.6 -0.4 0.6 -0.4z',
        'M1.2 -2c0 0 0.7 0 1.2 0.5c0.5 0.5 0.4 0.6 0.5 0.6c0.1 0 0.7 0 0.8 0.1c0.1 0 0.2 0.2 0.2 0.2c0 0 -0.6 0.2 -0.6 0.3c0 0.1 0.4 0.9 0.6 0.9c0.1 0 0.6 0 0.6 0.1c0 0.1 0 0.7 -0.1 0.7c-0.1 0 -1.2 0.4 -1.5 0.5c-0.3 0.1 -1.1 0.5 -1.1 0.7c-0.1 0.2 0.4 1.2 0.4 1.2l-0.4 0c0 0 -0.4 -0.8 -0.4 -0.9c0 -0.1 -0.1 -0.3 -0.1 -0.3l-0.2 0l-0.5 1.3l-0.4 0c0 0 -0.1 -0.4 0 -0.6c0.1 -0.1 0.3 -0.6 0.3 -0.7c0 0 -0.8 0 -1.5 -0.1c-0.7 -0.1 -1.2 -0.3 -1.2 -0.2c0 0.1 -0.4 0.6 -0.5 0.6c0 0 0.3 0.9 0.3 0.9l-0.4 0c0 0 -0.4 -0.5 -0.4 -0.6c0 -0.1 -0.2 -0.6 -0.2 -0.5c0 0 -0.4 0.4 -0.6 0.4c-0.2 0.1 -0.4 0.1 -0.4 0.1c0 0 -0.1 0.6 -0.1 0.6l-0.5 0l0 -1c0 0 0.5 -0.4 0.5 -0.5c0 -0.1 -0.7 -1.2 -0.6 -1.4c0.1 -0.1 0.1 -1.1 0.1 -1.1c0 0 -0.2 0.1 -0.2 0.1c0 0 0 0.9 0 1c0 0.1 -0.2 0.3 -0.3 0.3c-0.1 0 0 -0.5 0 -0.9c0 -0.4 0 -0.4 0.2 -0.6c0.2 -0.2 0.6 -0.3 0.8 -0.8c0.3 -0.5 1 -0.6 1 -0.6z',
        'M-4.1 -0.5c0.2 0 0.2 0.2 0.5 0.2c0.3 0 0.3 -0.2 0.5 -0.2c0.2 0 0.2 0.2 0.4 0.2c0.2 0 0.2 -0.2 0.5 -0.2c0.2 0 0.2 0.2 0.4 0.2c0.2 0 0.2 -0.2 0.4 -0.2c0.1 0 0.2 0.2 0.4 0.1c0.2 0 0.2 -0.2 0.4 -0.3c0.1 0 0.1 -0.1 0.4 0c0.3 0 0.3 -0.4 0.6 -0.4c0.3 0 0.6 -0.3 0.7 -0.2c0.1 0.1 1.4 1 1.3 1.4c-0.1 0.4 -0.3 0.3 -0.4 0.3c-0.1 0 -0.5 -0.4 -0.7 -0.2c-0.3 0.2 -0.1 0.4 -0.2 0.6c-0.1 0.1 -0.2 0.2 -0.3 0.4c0 0.2 0.1 0.3 0 0.5c-0.1 0.2 -0.3 0.2 -0.3 0.5c0 0.3 -0.2 0.3 -0.3 0.6c-0.1 0.2 0 0.3 -0.1 0.5c-0.1 0.2 -0.1 0.2 -0.2 0.3c-0.1 0.1 0.3 1.1 0.3 1.1l-0.3 0c0 0 -0.3 -0.9 -0.3 -1c0 -0.1 -0.1 -0.2 -0.3 -0.2c-0.2 0 -0.3 0.1 -0.4 0.4c0 0.3 -0.2 0.8 -0.2 0.8l-0.3 0l0.3 -1c0 0 0.1 -0.6 -0.2 -0.5c-0.3 0.1 -0.2 -0.1 -0.4 -0.1c-0.2 -0.1 -0.3 0.1 -0.4 0c-0.2 -0.1 -0.3 0.1 -0.5 0c-0.2 -0.1 -0.1 0 -0.3 0.3c-0.2 0.3 -0.4 0.3 -0.4 0.3l0.2 1.1l-0.3 0l-0.2 -1.1c0 0 -0.4 -0.6 -0.5 -0.4c-0.1 0.3 -0.1 0.4 -0.3 0.4c-0.1 -0.1 -0.2 1.1 -0.2 1.1l-0.3 0l0.2 -1.1c0 0 -0.3 -0.1 -0.3 -0.5c0 -0.3 0.1 -0.5 0.1 -0.7c0.1 -0.2 -0.1 -1 -0.2 -1.1c-0.1 -0.2 -0.2 -0.8 -0.2 -0.8c0 0 -0.1 -0.5 0.4 -0.8z'
    ]
)

color_scale = alt.Scale(
    domain=domains,
    range=['rgb(162,160,152)', 'rgb(194,81,64)', 'rgb(93,93,93)', 'rgb(91,131,149)']
)

alt.Chart(df).mark_point(filled=True).encode(
    alt.X('col:O', axis=None),
    alt.Y('animal:O', axis=None),
    alt.Row('country:N', header=alt.Header(title='')),
    alt.Shape('animal:N', legend=None, scale=shape_scale),
    alt.Color('animal:N', legend=None, scale=color_scale),
    alt.OpacityValue(1),
    alt.SizeValue(200)
).properties(width=800, height=200)
```

### CODE REVIEW

**Comment by chanwutk** [comment]
Hello @pratapvardhan,

Please credit to @jwoLondon for this example. The description and the original source are in the [examples.json](https://github.com/vega/vega-lite/blob/5be9dcce38f2ab501ffca7ad160a3d356affac40/_data/examples.json#L57-L61).

I'm very sorry for the confusion

**Comment by jakevdp** [comment]
That's awesome :smile:

Can you add a link to the Vega-Lite source in the description?

**Comment by pratapvardhan** [comment]
@jakevdp -- have added the reference.

**Comment by jakevdp** [comment]
Thanks - sorry to nitpick, but I think we should link to the vega-lite example rather than jwoLondon's github profile.

I believe once the vega docs are updated, the correct link will be https://vega.github.io/editor/#/examples/vega-lite/isotype_bar_chart, and we should feel free to add that link to Altair now. Thanks!

**Comment by pratapvardhan** [comment]
@jakevdp -- agreed, pushed the note.

**Comment by jakevdp** [comment]
Very nice. Thanks so much!

**Pull request merged**
