### PR TITLE
MAINT: add Python 3.7 support; remove Python 3.4 support

### PR DESCRIPTION
**Pull request by jakevdp**

### CODE REVIEW

**Comment by jakevdp** [comment]
Will revisit when 3.7 support is figured out in Travis/

**Comment by jakevdp** [comment]
Blocking issue is here: https://github.com/travis-ci/travis-ci/issues/9815

**Comment by jakevdp** [comment]
OK, got it working now... but because Python 3.7 requires a sudo=True build, it roughly quadruples the build time (from ~1.5 minutes to ~6 minutes.

I don't think it's worth that added cost at the moment. I'm going to hold-off on 3.7 support for the time being.

**Comment by hugovk** [comment]
I tried this branch and 3.7 errored:

```
3.7 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/16.04/x86_64/python-3.7.tar.bz2
$ curl -sSf -o python-3.7.tar.bz2 ${archive_url}
curl: (7) Failed to connect to s3.amazonaws.com port 443: Connection timed out
Unable to download 3.7 archive. The archive may not exist. Please consider a different version.
```

The curl command took 1m41s on my machine.

Rebuilding, 3.7 passed and took 1m33s (second fastest of them all):
https://travis-ci.org/hugovk/altair/jobs/420965493

Triggering a second build, 3.7 took 1m08s (the fastest):
https://travis-ci.org/hugovk/altair/builds/420967211

Triggering a third build, 3.7 took 1m19s (fastest again):
https://travis-ci.org/hugovk/altair/builds/420967441

I'm guessing perhaps there's some caching going on which may be slow first time round.

I suggest giving the PR another chance! :)

**Comment by hugovk** [comment]
And as it happens, my 3.5 build for https://github.com/altair-viz/altair/pull/1120 happened to take 4m55s. Looks like that was also an occasional slow download of the Python archive.

**Comment by jakevdp** [comment]
Thanks - I'll take a look!

**Comment by jakevdp** [comment]
Seems to be OK – thanks @hugovk!

**Pull request merged**
