### PR TITLE
This fixes some bugs and adds tests for the data transformers.

### PR DESCRIPTION
**Pull request by ellisonbg**
Pretty straightforward stuff. Right now, the data transformers are within the vegalite package. Most of these things will also be relevant to the vega side of things as well, but I will do that work in a separate PR once work on the vega API begins.

### CODE REVIEW

**Comment by jakevdp** [comment]
Sorry, I missed this somehow. Looks good. Is this invoked when data is saved to file as well?

**Comment by ellisonbg** [comment]
The `limit_rows` data transformer is only applied to the default transformation that does `to_values`. The `json` and `csv` ones, don't apply it, but a user could easily register a new one that did `sample` or `limit_rows` as well. I mad this choice as the performance issues appear to be much less critical when the data is written to files.

**Comment by jakevdp** [comment]
Makes sense. Feel free to merge if you're ready!

**Comment by ellisonbg** [comment]
Thanks! Merging.

**Pull request merged**
