### PR TITLE
ENH: Add Tukey Box Plot (1.5 IQR) example

### PR DESCRIPTION
**Pull request by pratapvardhan**
image

### CODE REVIEW

**Comment by jakevdp** [comment]
Hi - I think this is a bit too similar to https://github.com/altair-viz/altair/blob/master/altair/examples/boxplot_max_min.py to fit well in the example gallery.

This could be very helpful, though, as part of the narrative docs. It would be useful to demonstrate the various ``extent`` options in https://github.com/altair-viz/altair/blob/master/doc/user_guide/marks.rst

**Comment by pratapvardhan** [comment]
Agreed. I was replicating vega-lite example from https://vega.github.io/vega-lite/examples/boxplot_2D_vertical.html

I'll extend this to docs instead. Thanks.

**Comment by jakevdp** [comment]
Regarding the docs... I have a pretty big update in progress, fixing a number of vega-lite 3 incompatibilities. If you wait until that is in there will be fewer opportunities for merge conflicts.

**Comment by pratapvardhan** [comment]
@jakevdp -- understood, I'll wait up.

**Comment by jakevdp** [comment]
Relevant PR is here: #1397

**Comment by jakevdp** [comment]
Looks like this has stalled – if you'd like to pick it up again, feel free to re-open.

**Pull request closed without merging**
