### PR TITLE
Interactive scatter plot

### PR DESCRIPTION
**Pull request by afonit**
Added the interactive scatter plot as seen on vega-lite's site.
Everything worked except for adding the shape parameter.

### CODE REVIEW

**Comment by afonit** [comment]
I am sorry Jake, I see it is pulling into my other commits and other files changed.

I will stop pushing until I figure it out.

I was trying to only push the interactive example to origin.

I was following your video on:
https://www.youtube.com/watch?v=rgbCcBNZcdQ

**Comment by eitanlees** [comment]
I just did the same thing by accident. What went wrong was I created the new branch when I was not in the master branch. That means it keeps all of the changes and commits made before. What I ended up doing was going back to master and branching from there.

**Comment by afonit** [comment]
@eitanlees thank you so much for explaining that to me.
How did you go back and fix your previous branches so they only pushed the file you had changed in them?

**Comment by jakevdp** [comment]
To fix your previous branches, you'd have to undo the commits and then ``git push --force`` to overwrite what you've pushed here.

Might be easier just to create new branches

(plots look good thought! :smile:)

**Comment by afonit** [comment]
closing to fix beginner branching issues.

**Pull request closed without merging**
