### PR TITLE
docs: pandas -> Pandas

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by mattijn** [comment]
> When using the project name pandas, please use it in lower case, even at the beginning of a sentence.
See https://pandas.pydata.org/about/citing.html

**Comment by domoritz** [comment]
Today I learned. I always spelled it wrong then. 

Note that this page has other mentions of pandas and spells it as "Pandas". So we will want to update those, right?

**Comment by mattijn** [comment]
Trying to give them the right credits.. I also think they deserve a capital p;). 
I did a quick search and had 51 hits in the Altair docs where we use pandas with a capital p, so at least some of these require changing indeed..

**Comment by domoritz** [comment]
Thanks for making the changes. It looks odd to me as well but I prefer consistency over either option.

**Pull request closed without merging**
