### PR TITLE
Reorganized complex examples into a new case studies section

### PR DESCRIPTION
**Pull request by palewire**
As proposed in #883

### CODE REVIEW

**Comment by jakevdp** [comment]
I think users of the site might be confused by what "case studies" means in this context.

For example, we already have a "case studies" tab in the documentation that links to a narrative walkthrough of exploring a dataset using progressively more sophisticated charts. When you mentioned turning complicated charts into case studies, I thought you were talking about giving them that kind of treatment.

**Comment by jakevdp** [comment]
I do think it makes sense to somehow delineate between highly-tweaked charts and simple charts, though.

**Comment by jakevdp** [comment]
I think "Customized Charts" might make sense. Is that the main thing that separates these?

**Comment by kanitw** [comment]
FWIW, we plan to add "Customized Chart" / "Custom Visual Design" to Vega-Lite gallery too once we have a few more examples.

**Comment by palewire** [comment]
My thought is that this set is primarily about creating the best possible
chart to illustrate a particular dataset.

That is a contrast to the bulk of examples, which are the reverse: The best
possible dataset to illustrate a particular chart technique.

**Comment by jakevdp** [comment]
Sounds good – I think "case studies" will work then... it might be worth trying to add some mechanism to add summary text at the top of each example section, but that can come later.

Thanks!

**Pull request merged**
