### PR TITLE
added layered chart, bar and mark

### PR DESCRIPTION
**Pull request by afonit**
This could be prettier, I am playing around with the mark attributes but size does not seem to being doing anything.

This is a chart that I have been really waiting for to use in altair - I have been doing it in bokeh since I could not do it in altair.

It is a visual way to see how the goals (in red) are being met by current activity (the bars).

### CODE REVIEW

**Comment by jakevdp** [comment]
Very cool. One comment: we have a shortcut to creating layered charts:
```
chart = a + b
```

Also, it looks like the tick configuration has to happen via the top-level config setting. Something like this works:
```python
chart = a + b
chart.config = {'tick': {'thickness': 2, 'bandSize': 50}}
```

Altair 1 had ``configure_xxx()`` methods, which we should implement in Altair 2, so we could do something like 
```
chart = (a + b).configure_tick(thickness=2, bandSize=50)
```

**Comment by afonit** [comment]
Thanks for the recommendations.  I have added those.
I am looking through vegalite to see if there is a way to force a legend as that would be helpful in making the chart more understandable to have the labels 'score' and 'goal' show up.

**Comment by afonit** [comment]
I asked the vega-lite team since I don't see it in the docs:
https://github.com/vega/vega-lite/issues/3411

**Comment by afonit** [comment]
closing to fix some beginner mistakes with branching

**Pull request closed without merging**
