### PR TITLE
WIP: Lifting parameters to the top level

### PR DESCRIPTION
**Pull request by ChristopherDavisUCI**
Updated version of https://github.com/altair-viz/altair/pull/2671.  I believe the functionality is the same, but the code is a little cleaner.  @mattijn As always I am happy for any comments!

Here was the description of https://github.com/altair-viz/altair/pull/2671:

This is a draft version (some tests are currently failing) of the strategy suggested by @arvind and @mattijn [here](https://github.com/vega/vega-lite/issues/8230#issuecomment-1179607053) for dealing with parameters in multi-view Altair charts. We lift all parameters to the top level. In the case of selection parameters, we give the parameter a "views" property to indicate where the selections should be happening.

### CODE REVIEW

**Comment by ChristopherDavisUCI** [comment]
@mattijn I haven't worked on the Vega-Lite issues you raised in https://github.com/altair-viz/altair/pull/2671#issuecomment-1244085790.  If this code seems to be working for you (and not too complicated), I will start thinking about those issues.

Also if we decide this is working as expected, I will go through the 8 (?) failing tests and either change the tests or update my code.

**Comment by mattijn** [comment]
Great @ChristopherDavisUCI! Looks more readable. I like the changes. 

You might align these definitions:
https://github.com/ChristopherDavisUCI/altair/blob/liftparams/tools/generate_schema_wrapper.py#L29-L30

with the changes you introduced here: https://github.com/altair-viz/altair/blob/70682835bd4d80e31a378890f6f2274501cf2849/altair/vega/v5/schema/__init__.py

including a run of the `generate_schema_wrapper.py`, since:
```python
!python -m pip install git+https://github.com/ChristopherDavisUCI/altair.git@liftparams
import altair as alt
alt.SCHEMA_VERSION
```
gives me `v5.2.0`.

I checked a few of these failing tests and they seem to be related to the more recent discussion we had regarding the behaviour of layered params. These tests seems compact and interesting and I did not really see a case that require changing the tests assertion of these failing tests (excluding `interactive_layered_crossfilter.py`).

**Comment by ChristopherDavisUCI** [comment]
Thanks @mattijn!  I see now that I had updated the Vega version in the wrong place; it should be corrected now.  I also updated vega-lite to 5.5.0.  Does that sound like what you had in mind?  (It looks like the Vega-Lite editor uses vega-lite 5.2.0.)

I'll take a closer look at the failing tests soon.

**Comment by ChristopherDavisUCI** [comment]
@mattijn Here's one concern I have related to the failing tests.  If I understand right, the failing layer chart test, for example, asserts that adding a selection parameter to a LayerChart should be the same as adding a selection parameter to the first chart in the `layer` list.  I think that should be easy to implement, but what if a later version of Vega-Lite says these two parameter placements should both be allowed and should behave differently?  Do you see what I'm worried about?

If you think that sort of hypothetical future issue could be fixed easily enough later, I'll go ahead and try to add functionality so there is more flexibility in placing selection parameters on top level charts.

**Comment by ChristopherDavisUCI** [comment]
Hi @mattijn, I fixed three of the failing tests (for concat, hconcat, vconcat) by doing the following:
* Reverting to the previous code that, for any parameter added to the top level, distributes that parameter across the concat list.
* Resetting some instances of the Chart `_counter` in the test: https://github.com/altair-viz/altair/blob/c5fe43f9123ab95e1dd25418c1ec9c6f595a4a49/altair/vegalite/v5/tests/test_api.py#L630-L638) 

Does that all sound reasonable?  An alternative option to resetting the `_counter` would be to weaken the requirements that the dictionaries be identical.

**Comment by ChristopherDavisUCI** [comment]
Hi @mattijn, I think the only failing tests at this point are the two related to `test_interactive_layered_crossfilter`.  And as far as I understand, I don't think we know how to generate this chart with our current strategy.

Do you see a "parameters at the top level with named views" version of this Vega-Lite schema that is allowed? https://vega.github.io/vega-lite/examples/interactive_layered_crossfilter.html Or should we just resign ourselves to our strategy not working for this example at the moment?

**Comment by mattijn** [comment]
Great progress @ChristopherDavisUCI! Well done. 
Regarding the `repeat` operator, yes, let's not focus too much on this in this PR. 

I tried a few things and I think this is working pretty good. 

Still a question:
In https://github.com/altair-viz/altair/pull/2671#issuecomment-1244085790 there were 4 scenarios from which only scenario 1 was working. Now scenario 2 also works with the latest changes, but scenario 3 & 4 do still give errors. 

Do you think this is something that should be resolved within this PR?

**Comment by mattijn** [comment]
I had another go using `repeat` and `params`: https://github.com/vega/vega-lite/issues/6890#issuecomment-1266821631. It seems there is more possible than first anticipated.

**Comment by mattijn** [comment]
Yes I think so. We should be able at least a Vega-Lite spec that compiles. The interaction and axis will not be perfect, since these VL-bug(s): https://github.com/vega/vega-lite/issues/8446, which is hopefully a duplicate of https://github.com/vega/vega-lite/issues/8348, but we should be able to get a chart that renders.

If we instead focus on the Altair version of option 6, we can test better. 
Here the Altair spec with `repeat` commented out:
```python
!python -m pip install git+https://github.com/ChristopherDavisUCI/altair.git@liftparams
import pandas as pd
import altair as alt
source = pd.read_csv('https://unpkg.com/vega-datasets@1.25.0/data/weather.csv')

highlight = alt.selection_point(
    nearest=True, on="mouseover", encodings=["x"], clear="mouseout"
)
rule = (
    alt.Chart()
    .mark_rule()
    .encode(
        x=alt.X("month(date):T"),
        color=alt.value("black"),
        opacity=alt.condition(highlight, alt.value(1), alt.value(0), empty=False),
    )
)

line = (
    alt.Chart()
    .mark_line(point=True)
    .encode(
        x=alt.X("month(date):T"),
        y=alt.Y("mean(precipitation):Q"),  
        #y=alt.Y(alt.repeat('repeat'), aggregate='mean'),
        color=alt.Color("location:N"),
    )
)

alt.layer(rule, line, data=source, height=200, width=200).add_params(
    highlight
)#.repeat(repeat=["temp_max", "precipitation", "wind"])
```
If I add the `repeat` operator and change the `y` encoding to use the `repeat`, I get the following error:
```cmd
SchemaValidationError: Invalid specification

        altair.vegalite.v5.schema.channels.OpacityValue, validating 'additionalProperties'

        Additional properties are not allowed ('param', 'empty' were unexpected)
        
alt.RepeatChart(...)
```
This should compile, so we still miss something in the `alt.RepeatChart()`?

**Comment by ChristopherDavisUCI** [comment]
Hi @mattijn, thanks for the continued testing!  I think I got the RepeatChart issue fixed.  I haven't thought yet about your scenarios 3 and 4 that you mentioned in https://github.com/altair-viz/altair/pull/2671#issuecomment-1244085790 (but can confirm they're still not working).  I will think about that now.

Could you please take another look and see if things are now behaving mostly as you expected?

Is it obvious to you which tests have failed in the Python 3.9 build?  On my end they seem to be passing.

**Comment by mattijn** [comment]
Tests on Github Actions are failing because this PR in the `altair_viewer` repository is not yet merged: https://github.com/altair-viz/altair_viewer/pull/51.
I test your latests changes and all seems fine to me. Nice!
I noticed there is still one `assert` in your latest commits, you probably didn't want to include this: https://github.com/altair-viz/altair/pull/2684/commits/b79460deca9f7bb051d09956d1e8646f3c578c2e#diff-bbe4e187b18d242a366c820d023afd89041759cb96e4ec66c3f34559a72c2f9dR2332

**Comment by ChristopherDavisUCI** [comment]
Thanks as always for the feedback @mattijn.  I think your four scenarios from https://github.com/altair-viz/altair/pull/2671#issuecomment-1244085790 are currently working.
Could you please check and see if you agree?  Anything overall that seems not to be working?

**Comment by mattijn** [comment]
Nice as always @ChristopherDavisUCI! 
For the following layered facet chart, I still have two different errors. The first specification is a layered facet chart without parameters defined:
```python
import altair as alt
from vega_datasets import data

iris = data.iris.url
hover = alt.selection_point(on='mouseover', nearest=True)

base = alt.Chart().encode(
    x='petalLength:Q',
    y='petalWidth:Q',
    color='species:N'  # alt.condition(hover, 'species:N', alt.value('lightgray'))
).properties(
    width=180,
    height=180,
).add_params(hover)

points = base.mark_point()

text = base.mark_text(dy=-5).encode(
    text = 'species:N',
    opacity = alt.value(1)  # alt.condition(hover, alt.value(1), alt.value(0), empty=False)
)

chart = alt.layer(points, text, data=iris).facet(
    'species:N',
)  # .add_params(hover)

chart  # .to_dict()
```
Returns:
> ```cmd
> SchemaValidationError: Invalid specification
>         altair.vegalite.v5.api.Chart, validating 'required'
>         'data' is a required property        
> alt.FacetChart(...)
> ```
Not sure where I should add my data, I tried within `Chart()`, within `layer(data=iris`) and `facet(data=iris)`, but always the same error.

And the second layered facet chart including defined parameters:
```python
import altair as alt
from vega_datasets import data

iris = data.iris.url
hover = alt.selection_point(on='mouseover', nearest=True)

base = alt.Chart().encode(
    x='petalLength:Q',
    y='petalWidth:Q',
    color=alt.condition(hover, 'species:N', alt.value('lightgray'))  # 'species:N'
).properties(
    width=180,
    height=180,
).add_params(hover)

points = base.mark_point()

text = base.mark_text(dy=-5).encode(
    text='species:N',
    opacity=alt.condition(hover, alt.value(1), alt.value(0), empty=False)  # alt.value(1)
)

chart = alt.layer(points, text).facet(
    'species:N',
    data=iris
).add_params(hover)

chart  # .to_dict()`
```
Gives me:
> ```cmd
> SchemaValidationError: Invalid specification
>         altair.vegalite.v5.schema.channels.Color, validating 'additionalProperties'
>         Additional properties are not allowed ('param' was unexpected)        
> alt.FacetChart(...)
> ```

**Comment by ChristopherDavisUCI** [comment]
Thanks @mattijn!  These "data missing" error messages usually mean the parameters are in the wrong place, and that seems to be the case here.  I'll take a look.

**Comment by ChristopherDavisUCI** [comment]
Hi @mattijn, luckily it seems like the same fix that worked for LayerChart also works in this case.  Do your examples now seem to be working?  Please keep sending any non-working examples you can come up with!

**Comment by mattijn** [comment]
Does this work for you?:
```python
import altair as alt
from vega_datasets import data

iris = data.iris.url
hover = alt.selection_point(on='mouseover', nearest=True)

base = alt.Chart().encode(
    x='petalLength:Q',
    y='petalWidth:Q',
    color=alt.condition(hover, 'species:N', alt.value('lightgray'))
).properties(
    width=180,
    height=180,
).add_params(hover)

points = base.mark_point()

text = base.mark_text(dy=-5).encode(
    text='species:N',
    opacity=alt.condition(hover, alt.value(1), alt.value(0), empty=False)
)

chart = alt.layer(points, text, data=iris).facet(
    'species:N'
)

chart
```
For me not..

**Comment by ChristopherDavisUCI** [comment]
For me that example is working @mattijn.   (Or at least it displays without an error.)

When you run `print(chart.to_json())`, does the `params` property show up at the top level (that's where we want it)?  Maybe the GitHub repo hadn't fully updated when you tested it?

**Comment by mattijn** [comment]
Ah, yes! Latest commit didn't come properly through. Yes, this works now as well!

**Comment by ChristopherDavisUCI** [comment]
Great!  Please keep looking for examples that don't work as expected.

**Comment by mattijn** [comment]
This is not working, it resolves as option 3 from https://github.com/vega/vega-lite/issues/6890#issuecomment-1266821631. Probably outside the scope of this PR?
```python
import pandas as pd
import altair as alt

source_url = "https://unpkg.com/vega-datasets@1.25.0/data/weather.csv"

highlight = alt.selection_point(
    nearest=True, on="mouseover", encodings=["x"], clear="mouseout"
)

chart = alt.Chart(source_url).mark_circle().encode(
    x=alt.X("month(date):T"),
    color=alt.Color("location:N"),
    y=alt.Y(alt.repeat(), type="quantitative"),
    size=alt.condition(highlight, alt.value(200), alt.value(50), empty=False),
).repeat(["temp_max", "precipitation", "wind"]).add_params(highlight)

chart
```

**Comment by ChristopherDavisUCI** [comment]
Hmm, do you see what's wrong with the json that results from your example?  At first glance I would have expected this json to be correct.  [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUATJQAMlAFYQ2AOxAAaEFBUAzGmTShiNOAHcDmlZhrKGbBhAAScPVjQBmGTI1blVm3YgAdRoAE3o0ABZPAF9ojRwkACckBAg0AG1QZRS4NBAE5IQAfUl1EAg4QTgoTHMoKqS8hAC4O1qNOGUtEOsyNNR0kAAPEABdDWU4JLgIWtRMRIY4DRUmlrZSRLLMAE8cXPQcNmtauJAjU37Bi5MSsejxkES4faQ5wcxEHCLkEfjnqA0HB0N7sVQaEzWEJjDQQfZQcwhN4oVCgBiJQR5LC4fBEBjKHAAazIlC0CF4FH4SMwSAqmAgAAEAIxSCQyAjUpAEExTehwRKkiDEEBnTrdXp1NiCNhbVEgXSVaHoaVQUGrDS7fZ5ZRsBDWJCYs4QGgALwOoB8PSsqzlX12aG0Boq8SSKTyBRSdw0xANSzQkhi3t9BzEMjOIzlCsESpA1NyGpoCDgAFVlHQ1r4YNs9gcQJ8EEdkoaNDtzFGlaBnq85k8XryRRqc3kAI4MJC+EFWUgis7IRKEvKAxL1eMgbJJvI3O6xIA)

**Comment by mattijn** [comment]
Nope, reported here: https://github.com/vega/vega-lite/issues/8452

**Comment by mattijn** [comment]
I discovered two more issues that are not working:

First, `.interactive()` does not work in combination with `h`/`v`-`concat`:
```python
!python -m pip install git+https://github.com/ChristopherDavisUCI/altair.git@liftparams
import altair as alt
import pandas as pd

source = pd.read_csv('https://unpkg.com/vega-datasets@1.25.0/data/weather.csv')

# interval = alt.selection_interval(encodings=['x'], bind='scales')
line = (
    alt.Chart(height=100)
    .mark_bar(point=True)
    .encode(
        x=alt.X("date:T"),
        y=alt.Y("precipitation:Q"),
        color=alt.Color("location:N"),
    )
)
alt.vconcat(line, line, data=source).interactive(bind_y=False)  # .add_params(interval)
```

> ```cmd
> AttributeError: 'VConcatChart' object has no attribute 'interactive'
> ```

Second, I get a duplicate signal name error with the following:
```python

highlight = alt.selection_point(
    nearest=True, on="mouseover", encodings=["x"], clear="mouseout"
)
interval = alt.selection_interval(encodings=['x'], bind='scales')

line = (
    alt.Chart(height=100)
    .mark_line(point=True)
    .encode(
        x=alt.X("month(date):T"),
        y=alt.Y("mean(precipitation):Q"),
        color=alt.Color("location:N"),
    )
)  # .interactive(bind_y=False)  # add_params(interval)

rule = (
    alt.Chart()
    .mark_rule()
    .encode(
        x=alt.X("month(date):T"),
        color=alt.value("black"),
        opacity=alt.condition(highlight, alt.value(1), alt.value(0), empty=False),
    )
)

tick = (
    alt.Chart()
    .mark_tick(point=True)
    .encode(
        x=alt.X("month(date):T"),
        y=alt.Y("mean(precipitation):Q"),
        color=alt.Color("location:N"),
    )
)

alt.vconcat(line, tick + rule, data=source).add_params(
    highlight
)
```

> ```cmd
> Javascript Error: Duplicate signal name: "param_45_tuple"
> This usually means there's a typo in your chart specification. See the javascript console for the full traceback.
> ```

**Comment by ChristopherDavisUCI** [comment]
Thanks @mattijn I will check those out!  I always appreciate these bug examples.

By the way, it's slightly easier for me when you use the "url" data syntax, because then the json that's created is much more manageable.  So if it's ever easy to make that switch, please do!

**Comment by mattijn** [comment]
Will do!

**Comment by mattijn** [comment]
For me it make sense and the VL-scheme is OK with it. If defined on the concat level, the axis interaction will be done on both charts:



[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igbgxg9gdhCGAXEAuA2qAtvATga1VEQE8AHAU1RABsBLGSgGhFKnuRQDN5qBncgL7NycKABN6Ac0Iho1KDhmda5amKryEiWrBDMSFKjCiZ6PEEJAAPJSrVUxSJiAOUUL8plY5zl4rdV1d1IccghaUlpEJB0YPRcyNxAARwBXeBhtaO0wSgFLAAtyWkkCjgBGAAZK5hh4TCSwFQB3AH1yi0YsXAIUIkSqbQgCSxFoCRhpPtkoeUVp5UCNKC1Y+NcjEzNqTusA+3dHRGcN92OvBV9mfwW7IJBm8iQixX0B92NTOp385iKSsqoKo1EB1BpUJrkNoAJgsAF1mEd4DJUjgdu4yohSLwUAB6XGpGCkPCSAB00EwuNykngAFokfxELwAALlUnQgCspMquKRuMez3IOHJvDAu1IuHqvFQGFB9SSEp8mHa8X41DCHH6hnc7CFYHMwlEE0k0vQezhlgARvR7rwEOrpcxIc1TWhwC0VU6PbCLQiQAASO1FbBUTHYvFU8g00mSKIFVKW0k6XFBzzwSM02l0Y5UrlcyqkgBWvF0AiAA)

This is different compare to when defining on each sub-chart (which works already):


[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igbgxg9gdhCGAXEAuA2qAtvATga1VEQE8AHAU1RABsBLGSgGhFKnuRQDN5qBncgL7NycKABN6Ac0Iho1KDhmda5amKryEiWrBDMSFKjCiZ6PEEJAAPJSrVUxSJiAOUUL8plY5zl4rdV1d1IccghaUlpEJB0YPRcyNxAARwBXeBhtaO0wSgFLAAtyWkkCjgBGAAZK5hh4TCSwFQB3AH1yi0YsXAIUIkSqbQgCSxFoCRhpPtkoeUVp5UCNKC1Y+NcjEzNqTusA+3dHRGcN92OvBV9mfwW7IJBm8iQixX0B92NTOp385iKSsqoKo1EB1BpUJrkNoAJgsAF1mEd4DJUjgdu4yohSLwUAB6XGpGCkPCSAB00EwuNykngAFokfxELwAALlUnQgCspMquKRuMez3IOHJvDAu1IuHqvFQGFB9SSEp8mHa8X41DCHH6hnc7CFYHMwlEE0k0vQezhlgARvR7rwEOrpcxIc1TWhwC0VRaunLwcFJcrYcw1RqZKcQLqcPqdobxlJXearTaqHaeORHe6ofHna1YRaESAACR2orYKiY7F4qnkGmkyRRAqpS2knS44ueeBVmm0ujHKlcrmVUkAK14ugEQA)

Even with unequal axis name and type, this is OK on the concat: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9p3NATABDccgDaoALZKATgGs8IQgE8ADphQgARrpDdTEEqsI7SmOSExRIdEklQ8ADYQOobwmIF0lsHKxNB2RmYWyCBQEJokSoEgHgAeYViRlnQqFtwm5paEmJoOOlk53MYFEVEppjqYYHCmcIQqcPHlSZYAjqRKRH0DaBay3IwiCGIoAIwc3FBKmskgGDgA+quNWroGARW7NqH2jkQoLm4eXj5+hpDBoQHhRSkxA0NEpUUmkMltsnkWr8QNgSFFhsCQONJsR+sRZo0QM1voU2iAOl0etM4lAEpcxhMpmi4Bj5iBFqJVOsuKltrt9tgDgAmHIAXW4JX6hlIOmyKTEhFMlGQAHoZaQoKY9AgAHSQTQy2YIJQAWkFSkomEIlAAAqsVVyAKwqtgy-Uy7CYFSLHRqyhoTGmXTbSgoDSsnaWL31TRHBKGwJdVSgckpJyYHRoBrcF4QXxQBC+9QgfK8jxWOGWSjKSO++RYbBZtR7Cth8uHHl5-kgAAkxcW2ksEqlss1mG1KoQfUYpCsKsGMvbNSUfe1OsCfUwmut1rYKoAVpR4tIgA)

BTW, it's just a shortcut to the parameter variant (which works already):
```
interval = alt.selection_interval(encodings=['x'], bind='scales')
line = (
    alt.Chart(height=100)
    .mark_bar(point=True)
    .encode(
        x=alt.X("date:T"),
        y=alt.Y("precipitation:Q"),
        color=alt.Color("location:N"),
    )
)
alt.vconcat(line, line, data=source).add_params(interval)  # .interactive(bind_y=False)
``` 

For the second example regarding the duplicate signal, I think we had this issue before.
If I change `.mark_line(point=True)` to `.mark_line(point=False)` it works. See https://github.com/vega/vega-lite/issues/7854, but that Altair spec it refers to does work now already.. (https://github.com/altair-viz/altair/pull/2528#issuecomment-992989438)

**Comment by ChristopherDavisUCI** [comment]
Okay cool, should be no problem to add that `interactive` functionality then... just wanted to confirm that it wasn't something broken by this PR.

I haven't taken a look at the second example yet but will soon.

**Comment by ChristopherDavisUCI** [comment]
Hi @mattijn, could you please check and see if the concat `interactive` method is now working as you expected?

Regarding your second example, to me (maybe this is the same as you wrote) it seems like this is an issue on the Vega-Lite side, not the Altair side?  Or at least I thought this kind of parameter use was allowed.  (As a mnemonic, I believe your example has the form `alt.vconcat(view_1, alt.layer(view_2, view_3))` and we have a parameter on the top level with `views=[view_1, view_2]`.  I don't see why that would not be allowed.)  Does that match your understanding?

**Comment by mattijn** [comment]
Yes, that works great!

For the second chart, if I do:
```
alt.vconcat(line, (tick + rule).add_params(highlight), data=source)
``` 
it does work. But if I also add a highlight condition to the line then I run into issues again. There is some peculiarity with `point=True` in VL indeed. Upon manually defining a `mark_circle` in combination with a `mark_line` without `point=True`, our introduced logic does work as expected:

```python
source = "https://unpkg.com/vega-datasets@1.25.0/data/weather.csv"
highlight = alt.selection_point(
    name="hover",
    on="mouseover",
    nearest=True,
    encodings=["x"],
    empty=False,
    clear="mouseout",
)

top_base = alt.Chart(height=100, width=200).encode(
    x=alt.X("month(date):T"),
    y=alt.Y("mean(precipitation):Q"),
    color=alt.condition(highlight, alt.Color("location:N"), alt.value("gray")),
)

line = top_base.mark_line()
circle = top_base.mark_circle(size=100)


rule = (
    alt.Chart(height=100, width=200)
    .mark_rule(size=6)
    .encode(
        x=alt.X("month(date):T"),
        color=alt.value("black"),
        opacity=alt.condition(highlight, alt.value(1), alt.value(0)),
    )
)

tick = (
    alt.Chart()
    .mark_tick(thickness=5)
    .encode(
        x=alt.X("month(date):T"),
        y=alt.Y("mean(precipitation):Q"),
        color=alt.Color("location:N"),
    )
)

alt.vconcat((line + circle), (tick + rule), data=source).add_params(highlight)
```

Let's leave it with that for this.

One more question regarding docstrings, probably better for another PR, but I will still mention it.

Currently the docstrings for some new introduced parameter methods are rather limited:
image

Where in the above example I've defined it as such:
```python
highlight = alt.selection_point(
    name="hover",
    on="mouseover",
    nearest=True,
    encodings=["x"],
    empty=False,
    clear="mouseout",
)
```
How can one know about this without docstrings?

**Comment by mattijn** [comment]
Let me create an issue on the docstrings and the current limitation on repeat within the altair repo and then we can wait here until https://github.com/altair-viz/altair_viewer/pull/51 is merged so the Github Actions in this PR can be properly do their jobs (cc: @jakevdp).

**Comment by ChristopherDavisUCI** [comment]
Hi @mattijn, do you know, what is the analogue of `"child__row_petalLength"` when there is both a `row` and a `column` repeater?  I think I tried `"child__row_petalLength_column_sepalLength"`, `"child__row_petalLength__column_sepalLength"` and `"child__row_petalLengthchild__column_sepalLength"`, but as far as I can tell, none of those works.

**Comment by mattijn** [comment]
It is `child__row_petalLengthcolumn_sepalLength`. 

I modified the last chart under this section from the VL-docs here https://vega.github.io/vega-lite/docs/bind.html#scale-binding as an example, see: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICUJNohSZ8gL5KcppAghoA2qFkO4+stprLFICDhBOChMfRpZTDhtYiQ9JSYIv3RoOLgnJWIaOAB3J1RnEFgaQWUAfTLtNhyygAk2MzgcauioNkEGBFkygFkS9LKcaLKAcTjBOX9i0oqqmvrG5pzW9s7ugEEoKCDotXZ5JWnyyuq6hsCllY6us8WW7SmYEuO5ss3t4O09uTbr7r7ghBBsMxoIJgcik8Zicau8dl9MPtfms3lt4d8IUdZqc4Z8McibgsLvdHs9sTUAQMhtpRuMfqsbpSgdTaWDJocoS9TkzgTTQeCCRs0XjEezIWSYb1+syQXTZILbsTlg8ALpWFVKbRNOBqNCgOYuEBEpokpS43aiiE8ln8yYaooM+QFEDW2VsiHmhH7fzGy6qmwBIZQPUgZDaADW+maETCSjg8rYygiZBDAA8QwAzbKlENaoa69CCkABzAATyG+gAjgwkJE6HtSMWlKXM9nkvrtQWQAaS+XPOhq7XEepEY2lEhUzR8qAEBEAKKpqKRNAAZgADFYA78Gq2gskQAB5Hy0CFlivoWRsWfuPSbzdAA).
I'm not sure what happens if the column include spaces and/or other strange symbols. Probably requires escaping?

**Comment by ChristopherDavisUCI** [comment]
Thanks as always @mattijn!

I might start with a fresh PR once things seem to be working, but I think the latest commit has the repeat names working for plain repeats as well as repeats specifying "row" and/or "column".  (Should we be supporting anything else, like `alt.repeat(layer=???)`?)

@mattijn Can you work your usual magic and find charts that are not behaving as expected?

Is the following supposed to work?  It's not at the moment.  It produces this [Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUATJQAMlAFYQ2AOxAAaEFBUAzGmTShiNOAHcDmlZhrKGbBhAAScPVjQBmGTI1blVm3YgAdRoAE3o0ABZPAF9ojRCkTBRUUAYAJ0E0DGw8QgIGZRwAazJKLQReCn4EpIg4TAgAAQBGKQkZAhqkAhM4RPg0sohiEDiQHCQ0pAQINABtUGVpuCyJqYQAfTF1EDrBOChMcyh9yayEALg7I404ZS0Q6zJZ1DmQAA8QAF0NZT60uAQI6oTBpBhwDQqc6XNikNI7TAATxwK3QODY1iOYyMphebxxJi2OwJGwi32iPxAxB8UES81AdweT2ObEEbHhKRAujgghCWTZtKsUI0SJRWWUbAQ1iQmTGn053N5WRqKxFNAQcAAqso6NDfDAEcjUSBMIh0VNZRpEeYkGQyACKKbzn1VBpFXy0QCoDQcHREuxXSajVkAI4MJC+P1WUijMbwFzA5qeDTINJFczozFoUHgkXB9DCP6jX7LLIk7ZxUCCJCIuAchYgRlsR7KfScrRsjmgd38tiCgOGsXoCVSpaWj7mHvoFUI9VanXAkAXfWD42mhDmmXFkDWzm2+18J3oDURnZT8Zen1Rgd5ocgMMRqxJaMrWIpybpzmZ3zZsEQoN3lYUDpmMSwamWxiEmSlaNvczbMu2rLsuYxAyuCWRMNWwHbmwEzekiLLKI8QqqJyZoEag2gynUGhrNMqyTNMRIaKhgjoagzTYmhqIyHKk7GEq06JKqJpztqurHpYBq3muZrslub5Lh+WRgvsoxfBS0RAA)

```
import altair as alt

source = 'https://unpkg.com/vega-datasets@1.25.0/data/weather.csv'

highlight = alt.selection_point(
    nearest=True, on="mouseover", encodings=["x"], clear="mouseout"
)
interval = alt.selection_interval(encodings=['x'], bind='scales')

line = (
    alt.Chart(height=100)
    .mark_line(point=True)
    .encode(
        x=alt.X("month(date):T"),
        y=alt.Y("mean(precipitation):Q"),
        color=alt.Color("location:N"),
    )
)  # .interactive(bind_y=False)  # add_params(interval)

rule = (
    alt.Chart()
    .mark_rule()
    .encode(
        x=alt.X("month(date):T"),
        color=alt.value("black"),
        opacity=alt.condition(highlight, alt.value(1), alt.value(0), empty=False),
    )
)

tick = (
    alt.Chart()
    .mark_tick(point=True)
    .encode(
        x=alt.X("month(date):T"),
        y=alt.Y("mean(precipitation):Q"),
        color=alt.Color("location:N"),
    )
)

alt.vconcat(line, tick + rule, data=source).add_params(
    highlight
)
```

**Comment by mattijn** [comment]
Your last spec won't work as was concluded in https://github.com/altair-viz/altair/pull/2684#issuecomment-1278153027.

This spec:
```python
import altair as alt
from vega_datasets import data

source = data.movies.url

alt.Chart(source).mark_line().encode(
    x=alt.X(alt.repeat("column"), bin=True),
    # x=alt.X("IMDB_Rating:Q", bin=True),
    y=alt.Y(
        alt.repeat("layer"), aggregate="mean", title="Mean of US and Worldwide Gross"
    ),
    color=alt.ColorDatum(alt.repeat("layer")),
).repeat(
    layer=["US_Gross", "Worldwide_Gross"],
    column=["IMDB_Rating", "Rotten_Tomatoes_Rating"],
)  # .interactive()
```
Gives:
```cmd
ValueError: layer argument cannot be combined with row/column argument.
```
While it is allowed in VL: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAJgAY2AacaYsiygAlMiRoRQBGDgF9p3OgENCCvCFIAnADYoQYwgAdKyAPTGwdKADoAVpTqZNcNOstRMhY1H0BbY2kwICgC0isqU7pQAAmgSliwAnJZsxqEKxt4QGJiUNpTQIHIg6pj6mEqqmgoAnpjqKADaIACqAMoA+gDi6hCUlCDc1BBadNj0mJ3dvSAAutzduMiNAJIAsgAiAEJtAEpKJEjc2xCEhJhQbQAqEN5KENk7e1BI04WUpWCqUAremDpZ2G0JP0QDd1ABrHSONzAs6QOj7VSQTRDVShUjeVTFUrlZAgSo1OqybgAD1UACMSChCOpSJhuPAHHRMSUyuJcfMCoUqqoFAgEMVAqcdD8FFBgQzNEzUEUWTi8dVagVuMRCJpfrillBID9OYUACSUMCMTA3HR6QwmPwBBSWBBwJikMmWOAQYyG403K2BIKOU5+ACslkDbFy+WkQA). Technically not related to this PR though.

I cannot test what the behaviour of `.interactive()` should do, since this errors with a duplicate signal name on the VL side: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAJgAY2AacaYsiygAlMiRoRQBGDgF9p3OgENCCvCFIAnADYoQYwgAdKyAPTGwdKADoAVpTqZNcNOstRMhY1H0BbY2kwICgC0isqU7pQAAmgSliwAnJZsxqEKxt4QGJiUNpTQIHIg6pj6mEqqmgoAnpjqKADaIACqAMoA+gDi6hCUlCDc1BBadNj0mJ3dvSAAutzduMiNAJIAsgAiAEJtAEpKJEjc2xCEhJhQbQAqEN5KENk7e1BI04WUpWCqUAremDpZ2G0JP0QPoFOpvn1FqAvj8dKDwd5AcDwppMGBxKgQIQqqUdCRTuo0AptNwzpA6PtIY0qjNCgAjEh0HSUMDE7IFWYgG7qADWOkcbmBZIgFKeqkgmiGqlCpG8qmKpXKyBAlRqdVk3AAHqoGVAUIR1KRMNx4A4mZiFWUMUUILgNSAaZiFAgEMVAqcdD8FHqTVhNObQJalSrqrUCtxiIRUTollBILDZIUACQsxiYG46PSGEx+AIKSwIOBMUh0yxwCDGVPptL+QJBRynPwAVksLbYuXy0iAA), probably fixed by https://github.com/vega/vega-lite/pull/8486.

This spec also gives the same error on duplicate signals:
```python
#import altair as alt
source = 'https://unpkg.com/vega-datasets@1.25.0/data/weather.csv'

highlight = alt.selection_point(
    nearest=True, on="mouseover", encodings=["x"], clear="mouseout"
)
rule = (
    alt.Chart()
    .mark_rule()
    .encode(
        x=alt.X(alt.repeat('row'), bin=True),
        color=alt.value("black"),
        opacity=alt.condition(highlight, alt.value(1), alt.value(0), empty=False),
    )
)

line = (
    alt.Chart()
    .mark_line(point=True)
    .encode(
        x=alt.X(alt.repeat('row'), bin=True),
        y=alt.Y(alt.repeat('column'), bin=True),
        color=alt.Color("location:N"),
    )
)

alt.layer(line, rule, data=source, height=200, width=200).add_params(
    highlight
).repeat(column=["precipitation", "wind"], row=["temp_max", "precipitation"])#.to_dict()
```
But changing the order or `line` and `rule` in the `alt.layer` it does work (`alt.layer(rule, line, ...)`)...

I think we are done here.

**Comment by ChristopherDavisUCI** [comment]
Awesome, thanks again @mattijn.

I'm hoping to create a new PR so I can clean up some of the logic/ordering of the commits.

**Comment by ChristopherDavisUCI** [comment]
Closing this in favor of #2702.

**Pull request closed without merging**
