### PR TITLE
DOC: makes Chart.to_html more clear

### PR DESCRIPTION
**Pull request by stsievert**
This is a simple 3-line function that uses `to_html` to write an Altair chart to an HTML file.

### CODE REVIEW

**Comment by jakevdp** [comment]
Thanks for the contribution! Looking at this, I'm not sure this helper function is entirely necessary. You can accomplish the goals of this function with two straightforward lines of code, e.g.
```python
with open(filename) as f:
    f.write(chart.to_html())
```
I believe it would take most users longer to look-up the call signature to a specialized function than it would to simply write the code by hand.

**Comment by stsievert** [comment]
Ah, good point. I didn't realize that `Chart.to_html` existed because it didn't show up in IPython's autocomplete. I've added to README.md to give an example of it's usage (and reverted previous changes).

**Comment by jakevdp** [comment]
Thanks - this looks better. FWIW, the method is demonstrated in the tutorial as well. It might also be worth adding it to the auto-complete as well - just have to add it to the dir method of Chart.

**Comment by jakevdp** [comment]
Now that I look at it, I think the README is not the right place to add this information. The README is not meant to be project documentation or to contain comprehensive examples; it is meant to be a high-level package overview.

As I mentioned above, this information already exists in the package documentation linked from the README. Perhaps the issue is that this documentation is too difficult to find? If so, that might be something to think about.

**Comment by ellisonbg** [comment]
Yes, I would definitely perfer is the documentation is kept in the notebooks. For now I would edit the section of the Introduction notebook that has information about exporting to HTML...

**Comment by stsievert** [comment]
Ah, Introduction.ipynb is especially good. I've exposed this more by making the readme doc link bold and reordered cells in Index.ipynb.

I have also redefined `__dir__`, and added this definition to `TopLevelMixIn`. I avoided a recursive call by using `dir(type(self))` instead of `dir(self)`, which also has functions from super.

I have tested it and `to_html` and more functions appear in `__dir__` (and IPython's tab-completion). I only let public functions appear in `__dir__`.

**Comment by jakevdp** [comment]
Thanks – the problem with the ``public_funcs`` approach here is that because ``Chart`` eventually derives from ``traitlets.HasTraits``, there are a lot of public methods associated with this base class that we don't want to be part of the tab completion. That's why we had initially listed the methods by-hand.

**Comment by jakevdp** [comment]
Also, I think for the sake of IPython's tab completion, there's no need to explicitly ignore functions that start with an underscore, because these are skipped automatically. So in that sense, the solution here is essentially identical to leaving ``__dir__`` undefined.

**Comment by jakevdp** [comment]
Looks great! Thanks for keeping with this through all these iterations.

I think @ellisonbg can restart the tests – Assuming those pass, :+1: to merge this. @ellisonbg – do you see any issues with the approach @stsievert used for the ``__dir__`` function here? It looks good to me, but there may be some kind of corner-case that I'm overlooking. Thanks!

**Comment by stsievert** [comment]
I've rebased to resolve merge conflicts. @ellisonbg can you give this a look over for merge?

**Comment by jakevdp** [comment]
Sorry @stsievert, it looks like this conflicts with master again. If you can fix it I'll do a final review and merge.

**Comment by jakevdp** [comment]
I replaced some of the ``dir()`` specialization here in #259.

Since the doc updates are now out of date, I'm going to close the issue. Thanks @stsievert for your contribution, and sorry we didn't get it merged! Feel free to open a new PR if there are pieces of this you'd still like to add.

**Pull request closed without merging**
