### PR TITLE
WIP: update Vega-Lite to version 2.5

### PR DESCRIPTION
**Pull request by jakevdp**
A few tasks before merging

- [ ] ~wrap new field predicates~ (actually, field predicates are not wrapped at the moment; see #695)
- [x] handle ``.dsv`` data format
- [ ] deal with ``SortField`` backward incompatibility somehow?
- [x] update docs on above features

### CODE REVIEW

**Comment by jakevdp** [comment]
I can't think of any good way to deal with the ``SortField`` change. If ``SortField`` were now not used in the schema, we could alias it to ``EncodingSortField`` so that old code will continue working. But since ``SortField`` still exists but refers to something different, that will serve to create confusion in the case that someone wants to use the new version of ``SortField``.

I think we just need to stomach the API breakage and move on, though it will cause issues for some people when upgrading from 2.1 to 2.2.

I know @palewire has used ``SortField`` before, and others probably have too...

**Comment by kanitw** [comment]
We could think of another name and rename SortField in VL.

Ill be out of town for a week though so might nit be able to change that until i cole back

**Comment by palewire** [comment]
At this stage, I'm okay with eating API changes. I just wouldn't want to lose the functionality. What is it changing to?

**Comment by jakevdp** [comment]
OK, I think we'll just swallow the ``SortField`` -> ``EncodingSortField`` change at this point, then.

**Pull request merged**
