### PR TITLE
Documentation for each mark type

### PR DESCRIPTION
**Pull request by hebarton5**
This PR includes subpages for each mark. All content is based off of the vega-lite mark documentation (https://vega.github.io/vega-lite/docs/mark.html), with adjustments made to make it applicable to Altair.

### CODE REVIEW

**Comment by mattijn** [comment]
🎉👍

**Comment by joelostblom** [comment]
@hebarton5 Just checking in on this, would you be interested in working on addressing the comments I made?

**Comment by mattijn** [comment]
Or merge and accept as being "infrastructure code" and iterate further? I think this has been work part of an (given?) assignment.

**Comment by joelostblom** [comment]
Yeah, that makes sense, I won't have time to iterate on it for a while myself so maybe we should merge this when one of us have time to rewrite it so that these doc pages are not broken on the main branch?

**Comment by mattijn** [comment]
Make sense,  first fix conflicts before merging.

**Comment by binste** [comment]
@joelostblom I probably find some time during the next 4-5 weeks to address the open comments in this PR. However, I don't think I can edit this PR directly right? Could you merge it first or is there a better approach?

**Comment by mattijn** [comment]
I fixed the conflict. @binste, from here you can create a new PR to work on the review from @joelostblom. Thank you for for offering help.

**Pull request merged**
