### PR TITLE
Added a stacked bar chart example

### PR DESCRIPTION
**Pull request by eitanlees**
I tried recreating the canonical "weather type" bar chart.

### CODE REVIEW

**Comment by jakevdp** [comment]
Nice! One comment: if you do ``alt.X('date:N'`` to make the months nominal rather than temporal types, the bars will fill the whole space.

**Comment by eitanlees** [comment]
Interesting. I made the change, but on my end both charts looked the same.

**Comment by jakevdp** [comment]
Which vega-lite version are you using?

**Comment by eitanlees** [comment]
I am not sure how to check that. 

I am using Jupyter version 0.31.8 and Altair version '2.0.0dev'

I ran 
`jupyter labextension install @jupyterlab/vega3-extension` 
to get the display working.

**Comment by eitanlees** [comment]
I think I got confused. Now I see the difference. 

I tried setting up a conda env and a new Jupyter kernal and things got mixed up.  What a mess. 

I think I have things figured out now. Thanks

**Pull request merged**
