### PR TITLE
[WIP] Move to Vega-Lite 1.2

### PR DESCRIPTION
**Pull request by jakevdp**
Replaces #189

### CODE REVIEW

**Comment by jakevdp** [comment]
Failing because vega 0.4.3 is not yet on conda. Addressing this in https://github.com/conda-forge/vega-feedstock/pull/12

**Comment by jakevdp** [comment]
Rebased on master now that vega 0.4.3 builds are available

**Comment by jakevdp** [comment]
Alright, tests are passing!

@ellisonbg, any opposition to merging this and then doing a 1.2 release? I think it would be good to get that out ASAP, because the current version of ipyvega on pip and conda has some slight incompatibilities with the current version of altair.

**Comment by kanitw** [comment]
FYI, we just released [1.2.1](https://github.com/vega/vega-lite/releases/tag/v1.2.1), which mostly contains bug fixes and only one syntax addition ([DateTime object](http://vega.github.io/vega-lite/docs/transform.html#datetime) support for `scale`'s `domain` and `values` of `axis` and `legend`).  

@domoritz will probably update the ipyvega pretty soon.

**Comment by jakevdp** [comment]
OK, we'll wait for that.

**Comment by domoritz** [comment]
Done https://github.com/vega/ipyvega/releases/tag/v0.4.4

**Comment by jakevdp** [comment]
OK, this PR is compatible with VegaLite 1.2.1 now. Thanks @domoritz!

**Comment by ellisonbg** [comment]
+1 on this!

**Comment by jakevdp** [comment]
OK, I'll go merge then

**Pull request merged**
