### PR TITLE
Backport bug fixes for a 4.2.1 release

### PR DESCRIPTION
**Pull request by jtilly**
Hi everyone,

I'm a big fan of altair! Thanks for all your work on this.

I've read https://github.com/altair-viz/altair/discussions/2588, https://github.com/altair-viz/altair/issues/2768 and related issues and I was wondering if you'd be willing to make a 4.2.1 (or 4.3.0) release with bug fixes as long as I do all the work on it? (Or almost all of the work, because based on https://github.com/altair-viz/altair/issues/2793, one of you would still need to make the actual PyPI release).

In this PR, I'm backporting
- #2771 
- #2683  

and I bumped the version number and added a changlog entry.

I'm happy to backport more PRs that are fixing critical issues (if desired).

The PR is using `v4.2.X` as base branch.

Test suite is ✅  (after installing `altair_saver` and `'vega-lite-cli<5'` so that no tests are skipped).

<details>

```
pytest --pyargs --doctest-modules altair -x                                                           
============================================================================== test session starts ==============================================================================
platform darwin -- Python 3.11.0, pytest-7.2.0, pluggy-1.0.0
rootdir: /Users/jtilly/altair
plugins: xdist-3.1.0, cov-4.0.0
collected 605 items                                                                                                                                                             

altair/examples/tests/test_examples.py .................................................................................................................................. [ 21%]
......................................................................................................................................................................... [ 49%]
.............                                                                                                                                                             [ 51%]
altair/expr/tests/test_expr.py ..........                                                                                                                                 [ 53%]
altair/tests/test_magics.py .......                                                                                                                                       [ 54%]
altair/utils/core.py ..                                                                                                                                                   [ 54%]
altair/utils/deprecation.py .                                                                                                                                             [ 54%]
altair/utils/tests/test_core.py ..............                                                                                                                            [ 57%]
altair/utils/tests/test_data.py ........                                                                                                                                  [ 58%]
altair/utils/tests/test_deprecation.py ..                                                                                                                                 [ 58%]
altair/utils/tests/test_execeval.py ..                                                                                                                                    [ 59%]
altair/utils/tests/test_html.py ....                                                                                                                                      [ 59%]
altair/utils/tests/test_mimebundle.py ....                                                                                                                                [ 60%]
altair/utils/tests/test_plugin_registry.py ....                                                                                                                           [ 61%]
altair/utils/tests/test_schemapi.py ...................                                                                                                                   [ 64%]
altair/utils/tests/test_server.py .                                                                                                                                       [ 64%]
altair/utils/tests/test_utils.py ........                                                                                                                                 [ 65%]
altair/vega/tests/test_import.py .                                                                                                                                        [ 65%]
altair/vegalite/tests/test_common.py ........                                                                                                                             [ 67%]
altair/vegalite/v3/api.py ......                                                                                                                                          [ 68%]
altair/vegalite/v3/tests/test_api.py ................................................................................                                                     [ 81%]
altair/vegalite/v3/tests/test_data.py .                                                                                                                                   [ 81%]
altair/vegalite/v3/tests/test_display.py ..                                                                                                                               [ 81%]
altair/vegalite/v3/tests/test_geo_interface.py ........                                                                                                                   [ 83%]
altair/vegalite/v3/tests/test_renderers.py ...                                                                                                                            [ 83%]
altair/vegalite/v3/tests/test_theme.py .                                                                                                                                  [ 83%]
altair/vegalite/v4/api.py ......                                                                                                                                          [ 84%]
altair/vegalite/v4/tests/test_api.py ............................................................................                                                         [ 97%]
altair/vegalite/v4/tests/test_data.py .                                                                                                                                   [ 97%]
altair/vegalite/v4/tests/test_display.py ..                                                                                                                               [ 98%]
altair/vegalite/v4/tests/test_geo_interface.py ........                                                                                                                   [ 99%]
altair/vegalite/v4/tests/test_renderers.py ...                                                                                                                            [ 99%]
altair/vegalite/v4/tests/test_theme.py .                                                                                                                                  [100%]

======================================================================== 605 passed in 193.91s (0:03:13) ========================================================================
```

</details>

In https://github.com/altair-viz/altair/discussions/2588#discussioncomment-4346117, @joelostblom writes that 
> but it would require some reordering of the commits on the main branch

I'm not exactly sure what you mean by that and I would hope that it's fine to not have these bug fix commits in the correct order in the main branch.

If you're saying this is not worth the effort, feel free to close the PR.

### CODE REVIEW

**Comment by joelostblom** [comment]
Thanks for working on this @jtilly ! Regarding my previous comment, I think I made a more accurate one here https://github.com/altair-viz/altair/issues/2817#issuecomment-1374852750:

> Regarding a 4.3 version, I think there are some nice things with this, but it would involve a lot of rearranging **or** cherrypicking of commits to create the 4.3 release. I would rather spend that time on working toward a 5.0 release, and recommend people to update.

I guess between the two approaches it would make more sense to cherrypick the relevant commits into a separate branch (as you have here) and do a 4.3 release from that rather than trying to get the main branch in the right order.

As I mentioned in that comment, I do see advantage with a 4.3 release, but I don't have the bandwidth to put into work or review on that myself and would rather focus my efforts towards 5.0. Having that said, if someone else is willing to review, I definitely don't have anything against there being a 4.3/4.2.1 release with the most important bugfixes.

I would also like to draw your attention to https://github.com/altair-viz/altair/discussions/2599#discussioncomment-4582388, which mentions not all of the maintainers have the required  permissions to make a PyPI release, so if you are hoping to make a quick 4.3 release while waiting for 5.0, I am not sure if that will happen and it might be more likely that they both come out at a similar time (but that's a bit of speculation from my side, just wanted you to be aware of these caveats).

**Comment by jtilly** [comment]
> so if you are hoping to make a quick 4.3 release while waiting for 5.0, I am not sure if that will happen and it might be more likely that they both come out at a similar time 

That was my hope indeed 😁 

In any case, I wanted to give it a try -- please let me know if there are any other bug fixes that should be backported.

**Comment by th0ger** [comment]
Would love a patch for https://github.com/altair-viz/altair/pull/2771 soon, to avoid forcing `jsonschema<=4.16.0`.

**Comment by mattijn** [comment]
I think it is a good idea to prepare for a hotfixed version of altair 4.2. I also would like to include some warnings of features that will be removed in altair 5. 
Let me merge this PR first, as it looks solid to me.

**Pull request merged**
