### PR TITLE
Fix loading of schema on windows.

### PR DESCRIPTION
**Pull request by ajasja**
Import fails because schema is loaded with wrong encoding.

### CODE REVIEW

**Comment by jakevdp** [comment]
``schema/core.py`` is automatically generated by ``tools/generate_schema.py``, so we can't modify it directly like this – the change would be overwritten next time the code is regenerated.

Please make the change in ``tools``, then run the script to generate the code. If you'd prefer me to do it, please let me know!

**Comment by ajasja** [comment]
It should work now. I also committed the newly generated files.

**Comment by jakevdp** [comment]
It's strange to me that the diff is so massive here... I'd have expected it to just change the one line you originally changed. Maybe windows sorts things differently than unix systems?

**Comment by ajasja** [comment]
Does it matter which python version I used? The dicts are ordered in python
3 if I remember correctly. Perhaps you can try to generate the schema on
unix using the corrected  tools/generate_schema.py and see if there are any
differences?

**Comment by jakevdp** [comment]
OK, I added #638 which only changes a few lines. I'm still confused as to why the diffs are so big when you run it...

Please let me know whether the changes there fix your problem!

**Comment by jakevdp** [comment]
#638 is merged. I hope that fixes your issue!

**Comment by ajasja** [comment]
It should, but I did not have time to test it yet (have to finally install
python 3.6 at work as well:)

**Pull request closed without merging**
