### PR TITLE
Fix some formatting issues

### PR DESCRIPTION
**Pull request by binste**
Fixes two small formatting issues on the "Saving charts" doc page

### CODE REVIEW

**Review by joelostblom — APPROVED** [review]
Thanks!

**Comment by mattijn** [comment]
I thought it is `vl-convert-python`, see https://pypi.org/project/vl-convert-python/.

This line maybe explains the confusion:
> The `vl-convert-python` package provides a series of conversion functions under the `vl_convert` module.

There is variation in dash and underscore and package name and import name..

**Comment by joelostblom** [comment]
Yeah, that is technically the package name on PyPI but I think it makes sense to refer to it as "vl-convert" everywhere except where we note how to install it via `pip install vl-convert-python`. I don't care about it much though as long as the installation command is clear and the links are correct, so feel free to change it if you think that is more accurate

**Comment by ChristopherDavisUCI** [comment]
I've also found myself confused by that in the past... when to use dash and when to use underscore.  Right now vega-datasets is the only example I can think of, but it seems to trip me up regularly.

**Comment by mattijn** [comment]
> I think it makes sense to refer to it as "vl-convert" everywhere except where we note how to install it

I agree. It's good like this 👍.

**Pull request merged**
