### PR TITLE
Consolidate docs and add section on Large Datasets

### PR DESCRIPTION
**Pull request by binste**
Builds on discussion in #2738

@joelostblom I would not merge this yet but I already wanted to get your feedback, especially in case I don't get to the items below in the coming days. Outstanding from my side:

- [x] Find a good way to keep a Help indicator but deduplicate information which is currently on start page and on "Getting Help" -> Opted for moving "Getting Help" to "Getting Started" and removing some of the duplicated content on the start page.
- [x] Proofread the new content in "Large Datasets" and potentially extend
- [x] Provide examples on how to precalculate boxplots in Python and then plot in Altair. Other charts are more straightforward but I think this one would be helpful to have a reference implementation in the docs. For boxplot, see [Box Plot with Pre-Calculated Summaries](https://vega.github.io/vega-lite/docs/boxplot.html#box-plot-with-pre-calculated-summaries) on how to plot it

### CODE REVIEW

**Comment by joelostblom** [comment]
Thanks for starting this PR! I have a busy few days with work and traveling coming up so I am not sure exactly when I will get to this, but one thing I wanted to mention is that there is an Altair example for a box plot with pre-calculated summaries here https://stackoverflow.com/questions/59194197/how-to-change-altair-boxplot-infobox-to-display-mean-rather-than-median

**Comment by binste** [comment]
Sure, thanks for the heads-up and no worries! The PR is ready to review and the docs are built at https://binste.github.io/altair-docs/index.html

**Comment by mattijn** [comment]
I'd had a look to this as well and I think this looks great! Really helpful. Merging for now.

**Comment by mattijn** [comment]
Hi @binste, I noticed an issue with the Altair documentation site when viewed on a mobile phone. It appears that there may be a problem with the CSS styling, although I'm not sure if this is a new issue or if it has been happening for a while. I've included a screenshot for reference. This issue is not related to the current pull request.

image

**Pull request merged**
