### PR TITLE
Max rows

### LINKED ISSUE #281: Default Mark Property
I came accross a problem with the display of altair plots in Jupyter notebooks.
Take the following code, where df is any dataset:
    
    from altair import Chart
    Chart(df).to_dict().get('mark')
    
This would return 'point' in altair 1.0.0. In altair 1.2.0 this returns None, which results in a javascript error of the jupyter-vega extension and no display of the plot.

If the latter behavior is anticipated (i.e. the mark property of vega-lite plots may be undefined) the jupyter-vega extension would need a fix.

Niels

### PR DESCRIPTION
**Pull request by ellisonbg**
Fixes #281 

I still need to add the logic so this trait doesn't get serialized in the `to_dict` method.

Also @jakevdp where do we want to put traitlets like this that are not part of the spec? I put them direclty on the chart and other top level objects, but not sure that makes sense.

### CODE REVIEW

**Comment by ellisonbg** [comment]
And what number of rows is reasonable for the default max?

**Comment by jakevdp** [comment]
I think if you add ``maxrows`` to the ``skip`` list, it should keep it out of the serialization.

A default maximum of 5000 seems reasonable to me.

**Comment by ellisonbg** [comment]
OK I have made those changes and added a test to make sure that `max_rows` is not serialized. Should be ready to merge.

**Comment by jakevdp** [comment]
Looks good! Can you resolve the conflicts?

**Comment by ellisonbg** [comment]
k, rebased

**Comment by jakevdp** [comment]
Looks good!

**Pull request merged**
