### PR TITLE
Require traitlets 4.3.1

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Traitlets 4.3 fixes the issues that you reported wrt Union trait types. Error messages should now make sense.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
I don't think you need to pin the version with `==`. The 4.3 version fixed two issues with unions:

 - we have more meaningful error messages
 - we can set metadata for the union types (besides the metadata for the individual traits in the union). But you are not using metadata in altair.

**Comment by jakevdp** [comment]
OK – so it sounds like the main impact on users is better error messages in some cases.

Regarding metadata: do you see any places we should be using it where we aren't?

**Comment by SylvainCorlay** [comment]
> Regarding metadata: do you see any places we should be using it where we aren't?

In ipywidgets, we specify custom serializers and deserializers via metadata. (specified with the `tag` method). It seems that in altair, you are only using basic types that can be converted to json natively.

However, if you were to adopt custom trait types like [those](http://traittypes.readthedocs.io/en/latest/) you would need to specify the serialization.

I think that it would be interesting to converge in terms of how these things are serialized between the widgets and altair.

**Comment by jakevdp** [comment]
Good thoughts. Our handling of dataframes at the moment bypasses traitlets, and it would be nice to implement a cleaner solution.

**Comment by SylvainCorlay** [comment]
> Good thoughts. Our handling of dataframes at the moment bypasses traitlets, and it would be nice to implement a cleaner solution.

Then you can already use `traittypes.DataFrame` and specify a serializer that does the conversion you are doing manually, and a custom validation that only accepts the ones of the form that you accept (no hierarchical index).

```python
data = DataFrame().valid(no_hierachical)
```

where `no_hierarchical` is a callable that raises a trait error if the dataframe has a hierarchical index.

Example validating the shape of an array:

```python
from traitlets import HasTraits, TraitError
from traittypes import Array

def shape(*dimensions):
    def validator(trait, value):
        if value.shape != dimensions:
            raise TraitError('Expected an of shape %s and got and array with shape %s' % (dimensions, value.shape))
        else:
            return value
    return validator

class Foo(HasTraits):
    bar = Array(np.identity(2)).valid(shape(2, 2))
foo = Foo()

foo.bar = [1, 2]  # Should raise a TraitError
```

**Comment by SylvainCorlay** [comment]
The test failure is a network issue.

**Comment by jakevdp** [comment]
Could you make the same change in ``requirements.txt``?

**Comment by SylvainCorlay** [comment]
Done. Sorry for the oversight.

**Comment by jakevdp** [comment]
Will ``traittypes.DataFrame`` work within a union?

**Comment by SylvainCorlay** [comment]
Sure. However, if you use serializers in a union, they must be specified for each member of the union (since they are only valid for one or the other).

```python
foo = DataFrame().tag(to_json=my_df_to_json) | Dict(trait=List())
```

**Comment by jakevdp** [comment]
I actually didn't know you could use ``|`` to make a union :smile:

**Comment by jakevdp** [comment]
Thanks!

**Comment by jakevdp** [comment]
I'll chat with @ellisonbg at some point about moving to using traittypes.

**Pull request merged**
