### PR TITLE
Fix tz datetime

### LINKED ISSUE #926: Can't store pandas.DataFrame with column of datetime that has timezone
`sanitize_dataframe` does not understand data type datetime64[ns, UTC]
```python
data = pd.DataFrame(pd.date_range('2000-01-01',periods=5).tz_localize('UTC').rename('tz_datetime'))
print(data.info())
alt.Chart(data).mark_rule().encode(x='tz_datetime:T')
```
Out:
```python
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
tz_datetime    5 non-null datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1)
memory usage: 120.0 bytes
None
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/anaconda/anaconda/envs/rr_dev/lib/python3.5/site-packages/altair/vegalite/v2/api.py in to_dict(self, *args, **kwargs)
    312         copy = self.copy()
    313         original_data = getattr(copy, 'data', Undefined)
--> 314         copy.data = _prepare_data(original_data)
    315 
    316         # We make use of two context markers:

~/anaconda/anaconda/envs/rr_dev/lib/python3.5/site-packages/altair/vegalite/v2/api.py in _prepare_data(data)
     24         return data
     25     elif isinstance(data, pd.DataFrame):
---> 26         return pipe(data, data_transformers.get())
     27     elif isinstance(data, six.string_types):
     28         return core.UrlData(data)

~/anaconda/anaconda/envs/rr_dev/lib/python3.5/site-packages/toolz/functoolz.py in pipe(data, *funcs)
    550     """
    551     for func in funcs:
--> 552         data = func(data)
    553     return data
    554 

~/anaconda/anaconda/envs/rr_dev/lib/python3.5/site-packages/toolz/functoolz.py in __call__(self, *args, **kwargs)
    281     def __call__(self, *args, **kwargs):
    282         try:
--> 283             return self._partial(*args, **kwargs)
    284         except TypeError as exc:
    285             if self._should_curry(args, kwargs, exc):

~/anaconda/anaconda/envs/rr_dev/lib/python3.5/site-packages/altair/vegalite/data.py in default_data_transformer(data, max_rows)
     10 @curry
     11 def default_data_transformer(data, max_rows=5000):
---> 12     return pipe(data, limit_rows(max_rows=max_rows), to_values)
     13 
     14 

~/anaconda/anaconda/envs/rr_dev/lib/python3.5/site-packages/toolz/functoolz.py in pipe(data, *funcs)
    550     """
    551     for func in funcs:
--> 552         data = func(data)
    553     return data
    554 

~/anaconda/anaconda/envs/rr_dev/lib/python3.5/site-packages/toolz/functoolz.py in __call__(self, *args, **kwargs)
    281     def __call__(self, *args, **kwargs):
    282         try:
--> 283             return self._partial(*args, **kwargs)
    284         except TypeError as exc:
    285             if self._should_curry(args, kwargs, exc):

~/anaconda/anaconda/envs/rr_dev/lib/python3.5/site-packages/altair/utils/data.py in to_values(data)
    123     check_data_type(data)
    124     if isinstance(data, pd.DataFrame):
--> 125         data = sanitize_dataframe(data)
    126         return {'values': data.to_dict(orient='records')}
    127     elif isinstance(data, dict):

~/anaconda/anaconda/envs/rr_dev/lib/python3.5/site-packages/altair/utils/core.py in sanitize_dataframe(df)
     89             # convert numpy bools to objects; np.bool is not JSON serializable
     90             df[col_name] = df[col_name].astype(object)
---> 91         elif np.issubdtype(dtype, np.integer):
     92             # convert integers to objects; np.int is not JSON serializable
     93             df[col_name] = df[col_name].astype(object)

~/anaconda/anaconda/envs/rr_dev/lib/python3.5/site-packages/numpy/core/numerictypes.py in issubdtype(arg1, arg2)
    724     """
    725     if not issubclass_(arg1, generic):
--> 726         arg1 = dtype(arg1).type
    727     if not issubclass_(arg2, generic):
    728         arg2_orig = arg2

TypeError: data type not understood

Chart({
  data:                 tz_datetime
  0 2000-01-01 00:00:00+00:00
  1 2000-01-02 00:00:00+00:00
  2 2000-01-03 00:00:00+00:00
  3 2000-01-04 00:00:00+00:00
  4 2000-01-05 00:00:00+00:00
})
```
In:
```python
print('altair',alt.__version__)
print('pandas',pd.__version__)
print('numpy',np.__version__)
```
Out:
```python
altair 2.0.1
pandas 0.22.0
numpy 1.14.2
```
Same for 
```
altair 2.0.1
pandas 0.23.0
numpy 1.14.3
```

### PR DESCRIPTION
**Pull request by iliatimofeev**
fix #926

tests
+test_sanitize_dataframe()
+test_parse_shorthand_with_data()
code
sanitize_dataframe() -just reorder ifs

### CODE REVIEW

**Comment by jakevdp** [comment]
Thanks – so is the main issue that some datetimes are actually integer subtypes?

**Comment by iliatimofeev** [comment]
`np.issubdtype(data.dtypes['tz_datetime'], np.float)` will crush as well. It was just first call to `np.issubdtype` so it somehow crushes with "derived" types. I didn't do any deeper research on what causes that exception. I think it is some kind of misunderstanding between pandas and numpy.

**Comment by iliatimofeev** [comment]
Looks like it is a long discussion between them 
https://github.com/numpy/numpy/issues/9474
https://github.com/pandas-dev/pandas/issues/8814

**Comment by jakevdp** [comment]
OK, then it seems like this is probably the right fix – catch datetimes before any of the possible false triggers. Thanks for the fix here!

**Pull request merged**
